// ================================================================
// huffman_tables.svh
// Auto-generated by compute_huffman_dense.py — DO NOT EDIT MANUALLY
//
// Distribution : dense gradient (FREQS[0x00]=100)
// Avg code len : 7.862 bits  (raw = 8 bits)
// Compression  : 1.02x
// ================================================================

task config_encoder_full();
begin
    enc_wr_en = 1;
    @(posedge clk); enc_addr_config = 8'h00; enc_data_config = 20'h50000; // 0x00: len=5, code=00000
    @(posedge clk); enc_addr_config = 8'h01; enc_data_config = 20'h8001A; // 0x01: len=8, code=00011010
    @(posedge clk); enc_addr_config = 8'h02; enc_data_config = 20'h8001B; // 0x02: len=8, code=00011011
    @(posedge clk); enc_addr_config = 8'h03; enc_data_config = 20'h8001C; // 0x03: len=8, code=00011100
    @(posedge clk); enc_addr_config = 8'h04; enc_data_config = 20'h8001D; // 0x04: len=8, code=00011101
    @(posedge clk); enc_addr_config = 8'h05; enc_data_config = 20'h8001E; // 0x05: len=8, code=00011110
    @(posedge clk); enc_addr_config = 8'h06; enc_data_config = 20'h8001F; // 0x06: len=8, code=00011111
    @(posedge clk); enc_addr_config = 8'h07; enc_data_config = 20'h80020; // 0x07: len=8, code=00100000
    @(posedge clk); enc_addr_config = 8'h08; enc_data_config = 20'h80021; // 0x08: len=8, code=00100001
    @(posedge clk); enc_addr_config = 8'h09; enc_data_config = 20'h80022; // 0x09: len=8, code=00100010
    @(posedge clk); enc_addr_config = 8'h0A; enc_data_config = 20'h80023; // 0x0A: len=8, code=00100011
    @(posedge clk); enc_addr_config = 8'h0B; enc_data_config = 20'h80024; // 0x0B: len=8, code=00100100
    @(posedge clk); enc_addr_config = 8'h0C; enc_data_config = 20'h80025; // 0x0C: len=8, code=00100101
    @(posedge clk); enc_addr_config = 8'h0D; enc_data_config = 20'h80026; // 0x0D: len=8, code=00100110
    @(posedge clk); enc_addr_config = 8'h0E; enc_data_config = 20'h80027; // 0x0E: len=8, code=00100111
    @(posedge clk); enc_addr_config = 8'h0F; enc_data_config = 20'h80028; // 0x0F: len=8, code=00101000
    @(posedge clk); enc_addr_config = 8'h10; enc_data_config = 20'h901D8; // 0x10: len=9, code=111011000
    @(posedge clk); enc_addr_config = 8'h11; enc_data_config = 20'h901D9; // 0x11: len=9, code=111011001
    @(posedge clk); enc_addr_config = 8'h12; enc_data_config = 20'h901DA; // 0x12: len=9, code=111011010
    @(posedge clk); enc_addr_config = 8'h13; enc_data_config = 20'h901DB; // 0x13: len=9, code=111011011
    @(posedge clk); enc_addr_config = 8'h14; enc_data_config = 20'h901DC; // 0x14: len=9, code=111011100
    @(posedge clk); enc_addr_config = 8'h15; enc_data_config = 20'h901DD; // 0x15: len=9, code=111011101
    @(posedge clk); enc_addr_config = 8'h16; enc_data_config = 20'h901DE; // 0x16: len=9, code=111011110
    @(posedge clk); enc_addr_config = 8'h17; enc_data_config = 20'h901DF; // 0x17: len=9, code=111011111
    @(posedge clk); enc_addr_config = 8'h18; enc_data_config = 20'h901E0; // 0x18: len=9, code=111100000
    @(posedge clk); enc_addr_config = 8'h19; enc_data_config = 20'h901E1; // 0x19: len=9, code=111100001
    @(posedge clk); enc_addr_config = 8'h1A; enc_data_config = 20'h901E2; // 0x1A: len=9, code=111100010
    @(posedge clk); enc_addr_config = 8'h1B; enc_data_config = 20'h901E3; // 0x1B: len=9, code=111100011
    @(posedge clk); enc_addr_config = 8'h1C; enc_data_config = 20'h901E4; // 0x1C: len=9, code=111100100
    @(posedge clk); enc_addr_config = 8'h1D; enc_data_config = 20'h901E5; // 0x1D: len=9, code=111100101
    @(posedge clk); enc_addr_config = 8'h1E; enc_data_config = 20'h901E6; // 0x1E: len=9, code=111100110
    @(posedge clk); enc_addr_config = 8'h1F; enc_data_config = 20'h901E7; // 0x1F: len=9, code=111100111
    @(posedge clk); enc_addr_config = 8'h20; enc_data_config = 20'h901E8; // 0x20: len=9, code=111101000
    @(posedge clk); enc_addr_config = 8'h21; enc_data_config = 20'h901E9; // 0x21: len=9, code=111101001
    @(posedge clk); enc_addr_config = 8'h22; enc_data_config = 20'h901EA; // 0x22: len=9, code=111101010
    @(posedge clk); enc_addr_config = 8'h23; enc_data_config = 20'h901EB; // 0x23: len=9, code=111101011
    @(posedge clk); enc_addr_config = 8'h24; enc_data_config = 20'h901EC; // 0x24: len=9, code=111101100
    @(posedge clk); enc_addr_config = 8'h25; enc_data_config = 20'h901ED; // 0x25: len=9, code=111101101
    @(posedge clk); enc_addr_config = 8'h26; enc_data_config = 20'h901EE; // 0x26: len=9, code=111101110
    @(posedge clk); enc_addr_config = 8'h27; enc_data_config = 20'h901EF; // 0x27: len=9, code=111101111
    @(posedge clk); enc_addr_config = 8'h28; enc_data_config = 20'h901F0; // 0x28: len=9, code=111110000
    @(posedge clk); enc_addr_config = 8'h29; enc_data_config = 20'h901F1; // 0x29: len=9, code=111110001
    @(posedge clk); enc_addr_config = 8'h2A; enc_data_config = 20'h901F2; // 0x2A: len=9, code=111110010
    @(posedge clk); enc_addr_config = 8'h2B; enc_data_config = 20'h901F3; // 0x2B: len=9, code=111110011
    @(posedge clk); enc_addr_config = 8'h2C; enc_data_config = 20'h901F4; // 0x2C: len=9, code=111110100
    @(posedge clk); enc_addr_config = 8'h2D; enc_data_config = 20'h901F5; // 0x2D: len=9, code=111110101
    @(posedge clk); enc_addr_config = 8'h2E; enc_data_config = 20'h901F6; // 0x2E: len=9, code=111110110
    @(posedge clk); enc_addr_config = 8'h2F; enc_data_config = 20'h901F7; // 0x2F: len=9, code=111110111
    @(posedge clk); enc_addr_config = 8'h30; enc_data_config = 20'h901F8; // 0x30: len=9, code=111111000
    @(posedge clk); enc_addr_config = 8'h31; enc_data_config = 20'h901F9; // 0x31: len=9, code=111111001
    @(posedge clk); enc_addr_config = 8'h32; enc_data_config = 20'h901FA; // 0x32: len=9, code=111111010
    @(posedge clk); enc_addr_config = 8'h33; enc_data_config = 20'h901FB; // 0x33: len=9, code=111111011
    @(posedge clk); enc_addr_config = 8'h34; enc_data_config = 20'h901FC; // 0x34: len=9, code=111111100
    @(posedge clk); enc_addr_config = 8'h35; enc_data_config = 20'h901FD; // 0x35: len=9, code=111111101
    @(posedge clk); enc_addr_config = 8'h36; enc_data_config = 20'h901FE; // 0x36: len=9, code=111111110
    @(posedge clk); enc_addr_config = 8'h37; enc_data_config = 20'h901FF; // 0x37: len=9, code=111111111
    @(posedge clk); enc_addr_config = 8'h38; enc_data_config = 20'h80029; // 0x38: len=8, code=00101001
    @(posedge clk); enc_addr_config = 8'h39; enc_data_config = 20'h8002A; // 0x39: len=8, code=00101010
    @(posedge clk); enc_addr_config = 8'h3A; enc_data_config = 20'h8002B; // 0x3A: len=8, code=00101011
    @(posedge clk); enc_addr_config = 8'h3B; enc_data_config = 20'h8002C; // 0x3B: len=8, code=00101100
    @(posedge clk); enc_addr_config = 8'h3C; enc_data_config = 20'h8002D; // 0x3C: len=8, code=00101101
    @(posedge clk); enc_addr_config = 8'h3D; enc_data_config = 20'h8002E; // 0x3D: len=8, code=00101110
    @(posedge clk); enc_addr_config = 8'h3E; enc_data_config = 20'h8002F; // 0x3E: len=8, code=00101111
    @(posedge clk); enc_addr_config = 8'h3F; enc_data_config = 20'h60002; // 0x3F: len=6, code=000010
    @(posedge clk); enc_addr_config = 8'h40; enc_data_config = 20'h60003; // 0x40: len=6, code=000011
    @(posedge clk); enc_addr_config = 8'h41; enc_data_config = 20'h80030; // 0x41: len=8, code=00110000
    @(posedge clk); enc_addr_config = 8'h42; enc_data_config = 20'h80031; // 0x42: len=8, code=00110001
    @(posedge clk); enc_addr_config = 8'h43; enc_data_config = 20'h80032; // 0x43: len=8, code=00110010
    @(posedge clk); enc_addr_config = 8'h44; enc_data_config = 20'h80033; // 0x44: len=8, code=00110011
    @(posedge clk); enc_addr_config = 8'h45; enc_data_config = 20'h80034; // 0x45: len=8, code=00110100
    @(posedge clk); enc_addr_config = 8'h46; enc_data_config = 20'h80035; // 0x46: len=8, code=00110101
    @(posedge clk); enc_addr_config = 8'h47; enc_data_config = 20'h80036; // 0x47: len=8, code=00110110
    @(posedge clk); enc_addr_config = 8'h48; enc_data_config = 20'h80037; // 0x48: len=8, code=00110111
    @(posedge clk); enc_addr_config = 8'h49; enc_data_config = 20'h80038; // 0x49: len=8, code=00111000
    @(posedge clk); enc_addr_config = 8'h4A; enc_data_config = 20'h80039; // 0x4A: len=8, code=00111001
    @(posedge clk); enc_addr_config = 8'h4B; enc_data_config = 20'h8003A; // 0x4B: len=8, code=00111010
    @(posedge clk); enc_addr_config = 8'h4C; enc_data_config = 20'h8003B; // 0x4C: len=8, code=00111011
    @(posedge clk); enc_addr_config = 8'h4D; enc_data_config = 20'h8003C; // 0x4D: len=8, code=00111100
    @(posedge clk); enc_addr_config = 8'h4E; enc_data_config = 20'h8003D; // 0x4E: len=8, code=00111101
    @(posedge clk); enc_addr_config = 8'h4F; enc_data_config = 20'h8003E; // 0x4F: len=8, code=00111110
    @(posedge clk); enc_addr_config = 8'h50; enc_data_config = 20'h8003F; // 0x50: len=8, code=00111111
    @(posedge clk); enc_addr_config = 8'h51; enc_data_config = 20'h80040; // 0x51: len=8, code=01000000
    @(posedge clk); enc_addr_config = 8'h52; enc_data_config = 20'h80041; // 0x52: len=8, code=01000001
    @(posedge clk); enc_addr_config = 8'h53; enc_data_config = 20'h80042; // 0x53: len=8, code=01000010
    @(posedge clk); enc_addr_config = 8'h54; enc_data_config = 20'h80043; // 0x54: len=8, code=01000011
    @(posedge clk); enc_addr_config = 8'h55; enc_data_config = 20'h80044; // 0x55: len=8, code=01000100
    @(posedge clk); enc_addr_config = 8'h56; enc_data_config = 20'h80045; // 0x56: len=8, code=01000101
    @(posedge clk); enc_addr_config = 8'h57; enc_data_config = 20'h80046; // 0x57: len=8, code=01000110
    @(posedge clk); enc_addr_config = 8'h58; enc_data_config = 20'h80047; // 0x58: len=8, code=01000111
    @(posedge clk); enc_addr_config = 8'h59; enc_data_config = 20'h80048; // 0x59: len=8, code=01001000
    @(posedge clk); enc_addr_config = 8'h5A; enc_data_config = 20'h80049; // 0x5A: len=8, code=01001001
    @(posedge clk); enc_addr_config = 8'h5B; enc_data_config = 20'h8004A; // 0x5B: len=8, code=01001010
    @(posedge clk); enc_addr_config = 8'h5C; enc_data_config = 20'h8004B; // 0x5C: len=8, code=01001011
    @(posedge clk); enc_addr_config = 8'h5D; enc_data_config = 20'h8004C; // 0x5D: len=8, code=01001100
    @(posedge clk); enc_addr_config = 8'h5E; enc_data_config = 20'h8004D; // 0x5E: len=8, code=01001101
    @(posedge clk); enc_addr_config = 8'h5F; enc_data_config = 20'h8004E; // 0x5F: len=8, code=01001110
    @(posedge clk); enc_addr_config = 8'h60; enc_data_config = 20'h8004F; // 0x60: len=8, code=01001111
    @(posedge clk); enc_addr_config = 8'h61; enc_data_config = 20'h80050; // 0x61: len=8, code=01010000
    @(posedge clk); enc_addr_config = 8'h62; enc_data_config = 20'h80051; // 0x62: len=8, code=01010001
    @(posedge clk); enc_addr_config = 8'h63; enc_data_config = 20'h80052; // 0x63: len=8, code=01010010
    @(posedge clk); enc_addr_config = 8'h64; enc_data_config = 20'h80053; // 0x64: len=8, code=01010011
    @(posedge clk); enc_addr_config = 8'h65; enc_data_config = 20'h80054; // 0x65: len=8, code=01010100
    @(posedge clk); enc_addr_config = 8'h66; enc_data_config = 20'h80055; // 0x66: len=8, code=01010101
    @(posedge clk); enc_addr_config = 8'h67; enc_data_config = 20'h80056; // 0x67: len=8, code=01010110
    @(posedge clk); enc_addr_config = 8'h68; enc_data_config = 20'h80057; // 0x68: len=8, code=01010111
    @(posedge clk); enc_addr_config = 8'h69; enc_data_config = 20'h80058; // 0x69: len=8, code=01011000
    @(posedge clk); enc_addr_config = 8'h6A; enc_data_config = 20'h80059; // 0x6A: len=8, code=01011001
    @(posedge clk); enc_addr_config = 8'h6B; enc_data_config = 20'h8005A; // 0x6B: len=8, code=01011010
    @(posedge clk); enc_addr_config = 8'h6C; enc_data_config = 20'h8005B; // 0x6C: len=8, code=01011011
    @(posedge clk); enc_addr_config = 8'h6D; enc_data_config = 20'h8005C; // 0x6D: len=8, code=01011100
    @(posedge clk); enc_addr_config = 8'h6E; enc_data_config = 20'h8005D; // 0x6E: len=8, code=01011101
    @(posedge clk); enc_addr_config = 8'h6F; enc_data_config = 20'h8005E; // 0x6F: len=8, code=01011110
    @(posedge clk); enc_addr_config = 8'h70; enc_data_config = 20'h8005F; // 0x70: len=8, code=01011111
    @(posedge clk); enc_addr_config = 8'h71; enc_data_config = 20'h80060; // 0x71: len=8, code=01100000
    @(posedge clk); enc_addr_config = 8'h72; enc_data_config = 20'h80061; // 0x72: len=8, code=01100001
    @(posedge clk); enc_addr_config = 8'h73; enc_data_config = 20'h80062; // 0x73: len=8, code=01100010
    @(posedge clk); enc_addr_config = 8'h74; enc_data_config = 20'h80063; // 0x74: len=8, code=01100011
    @(posedge clk); enc_addr_config = 8'h75; enc_data_config = 20'h80064; // 0x75: len=8, code=01100100
    @(posedge clk); enc_addr_config = 8'h76; enc_data_config = 20'h80065; // 0x76: len=8, code=01100101
    @(posedge clk); enc_addr_config = 8'h77; enc_data_config = 20'h80066; // 0x77: len=8, code=01100110
    @(posedge clk); enc_addr_config = 8'h78; enc_data_config = 20'h80067; // 0x78: len=8, code=01100111
    @(posedge clk); enc_addr_config = 8'h79; enc_data_config = 20'h80068; // 0x79: len=8, code=01101000
    @(posedge clk); enc_addr_config = 8'h7A; enc_data_config = 20'h80069; // 0x7A: len=8, code=01101001
    @(posedge clk); enc_addr_config = 8'h7B; enc_data_config = 20'h8006A; // 0x7B: len=8, code=01101010
    @(posedge clk); enc_addr_config = 8'h7C; enc_data_config = 20'h8006B; // 0x7C: len=8, code=01101011
    @(posedge clk); enc_addr_config = 8'h7D; enc_data_config = 20'h8006C; // 0x7D: len=8, code=01101100
    @(posedge clk); enc_addr_config = 8'h7E; enc_data_config = 20'h8006D; // 0x7E: len=8, code=01101101
    @(posedge clk); enc_addr_config = 8'h7F; enc_data_config = 20'h8006E; // 0x7F: len=8, code=01101110
    @(posedge clk); enc_addr_config = 8'h80; enc_data_config = 20'h60004; // 0x80: len=6, code=000100
    @(posedge clk); enc_addr_config = 8'h81; enc_data_config = 20'h8006F; // 0x81: len=8, code=01101111
    @(posedge clk); enc_addr_config = 8'h82; enc_data_config = 20'h80070; // 0x82: len=8, code=01110000
    @(posedge clk); enc_addr_config = 8'h83; enc_data_config = 20'h80071; // 0x83: len=8, code=01110001
    @(posedge clk); enc_addr_config = 8'h84; enc_data_config = 20'h80072; // 0x84: len=8, code=01110010
    @(posedge clk); enc_addr_config = 8'h85; enc_data_config = 20'h80073; // 0x85: len=8, code=01110011
    @(posedge clk); enc_addr_config = 8'h86; enc_data_config = 20'h80074; // 0x86: len=8, code=01110100
    @(posedge clk); enc_addr_config = 8'h87; enc_data_config = 20'h80075; // 0x87: len=8, code=01110101
    @(posedge clk); enc_addr_config = 8'h88; enc_data_config = 20'h80076; // 0x88: len=8, code=01110110
    @(posedge clk); enc_addr_config = 8'h89; enc_data_config = 20'h80077; // 0x89: len=8, code=01110111
    @(posedge clk); enc_addr_config = 8'h8A; enc_data_config = 20'h80078; // 0x8A: len=8, code=01111000
    @(posedge clk); enc_addr_config = 8'h8B; enc_data_config = 20'h80079; // 0x8B: len=8, code=01111001
    @(posedge clk); enc_addr_config = 8'h8C; enc_data_config = 20'h8007A; // 0x8C: len=8, code=01111010
    @(posedge clk); enc_addr_config = 8'h8D; enc_data_config = 20'h8007B; // 0x8D: len=8, code=01111011
    @(posedge clk); enc_addr_config = 8'h8E; enc_data_config = 20'h8007C; // 0x8E: len=8, code=01111100
    @(posedge clk); enc_addr_config = 8'h8F; enc_data_config = 20'h8007D; // 0x8F: len=8, code=01111101
    @(posedge clk); enc_addr_config = 8'h90; enc_data_config = 20'h8007E; // 0x90: len=8, code=01111110
    @(posedge clk); enc_addr_config = 8'h91; enc_data_config = 20'h8007F; // 0x91: len=8, code=01111111
    @(posedge clk); enc_addr_config = 8'h92; enc_data_config = 20'h80080; // 0x92: len=8, code=10000000
    @(posedge clk); enc_addr_config = 8'h93; enc_data_config = 20'h80081; // 0x93: len=8, code=10000001
    @(posedge clk); enc_addr_config = 8'h94; enc_data_config = 20'h80082; // 0x94: len=8, code=10000010
    @(posedge clk); enc_addr_config = 8'h95; enc_data_config = 20'h80083; // 0x95: len=8, code=10000011
    @(posedge clk); enc_addr_config = 8'h96; enc_data_config = 20'h80084; // 0x96: len=8, code=10000100
    @(posedge clk); enc_addr_config = 8'h97; enc_data_config = 20'h80085; // 0x97: len=8, code=10000101
    @(posedge clk); enc_addr_config = 8'h98; enc_data_config = 20'h80086; // 0x98: len=8, code=10000110
    @(posedge clk); enc_addr_config = 8'h99; enc_data_config = 20'h80087; // 0x99: len=8, code=10000111
    @(posedge clk); enc_addr_config = 8'h9A; enc_data_config = 20'h80088; // 0x9A: len=8, code=10001000
    @(posedge clk); enc_addr_config = 8'h9B; enc_data_config = 20'h80089; // 0x9B: len=8, code=10001001
    @(posedge clk); enc_addr_config = 8'h9C; enc_data_config = 20'h8008A; // 0x9C: len=8, code=10001010
    @(posedge clk); enc_addr_config = 8'h9D; enc_data_config = 20'h8008B; // 0x9D: len=8, code=10001011
    @(posedge clk); enc_addr_config = 8'h9E; enc_data_config = 20'h8008C; // 0x9E: len=8, code=10001100
    @(posedge clk); enc_addr_config = 8'h9F; enc_data_config = 20'h8008D; // 0x9F: len=8, code=10001101
    @(posedge clk); enc_addr_config = 8'hA0; enc_data_config = 20'h8008E; // 0xA0: len=8, code=10001110
    @(posedge clk); enc_addr_config = 8'hA1; enc_data_config = 20'h8008F; // 0xA1: len=8, code=10001111
    @(posedge clk); enc_addr_config = 8'hA2; enc_data_config = 20'h80090; // 0xA2: len=8, code=10010000
    @(posedge clk); enc_addr_config = 8'hA3; enc_data_config = 20'h80091; // 0xA3: len=8, code=10010001
    @(posedge clk); enc_addr_config = 8'hA4; enc_data_config = 20'h80092; // 0xA4: len=8, code=10010010
    @(posedge clk); enc_addr_config = 8'hA5; enc_data_config = 20'h80093; // 0xA5: len=8, code=10010011
    @(posedge clk); enc_addr_config = 8'hA6; enc_data_config = 20'h80094; // 0xA6: len=8, code=10010100
    @(posedge clk); enc_addr_config = 8'hA7; enc_data_config = 20'h80095; // 0xA7: len=8, code=10010101
    @(posedge clk); enc_addr_config = 8'hA8; enc_data_config = 20'h80096; // 0xA8: len=8, code=10010110
    @(posedge clk); enc_addr_config = 8'hA9; enc_data_config = 20'h80097; // 0xA9: len=8, code=10010111
    @(posedge clk); enc_addr_config = 8'hAA; enc_data_config = 20'h80098; // 0xAA: len=8, code=10011000
    @(posedge clk); enc_addr_config = 8'hAB; enc_data_config = 20'h80099; // 0xAB: len=8, code=10011001
    @(posedge clk); enc_addr_config = 8'hAC; enc_data_config = 20'h8009A; // 0xAC: len=8, code=10011010
    @(posedge clk); enc_addr_config = 8'hAD; enc_data_config = 20'h8009B; // 0xAD: len=8, code=10011011
    @(posedge clk); enc_addr_config = 8'hAE; enc_data_config = 20'h8009C; // 0xAE: len=8, code=10011100
    @(posedge clk); enc_addr_config = 8'hAF; enc_data_config = 20'h8009D; // 0xAF: len=8, code=10011101
    @(posedge clk); enc_addr_config = 8'hB0; enc_data_config = 20'h8009E; // 0xB0: len=8, code=10011110
    @(posedge clk); enc_addr_config = 8'hB1; enc_data_config = 20'h8009F; // 0xB1: len=8, code=10011111
    @(posedge clk); enc_addr_config = 8'hB2; enc_data_config = 20'h800A0; // 0xB2: len=8, code=10100000
    @(posedge clk); enc_addr_config = 8'hB3; enc_data_config = 20'h800A1; // 0xB3: len=8, code=10100001
    @(posedge clk); enc_addr_config = 8'hB4; enc_data_config = 20'h800A2; // 0xB4: len=8, code=10100010
    @(posedge clk); enc_addr_config = 8'hB5; enc_data_config = 20'h800A3; // 0xB5: len=8, code=10100011
    @(posedge clk); enc_addr_config = 8'hB6; enc_data_config = 20'h800A4; // 0xB6: len=8, code=10100100
    @(posedge clk); enc_addr_config = 8'hB7; enc_data_config = 20'h800A5; // 0xB7: len=8, code=10100101
    @(posedge clk); enc_addr_config = 8'hB8; enc_data_config = 20'h800A6; // 0xB8: len=8, code=10100110
    @(posedge clk); enc_addr_config = 8'hB9; enc_data_config = 20'h800A7; // 0xB9: len=8, code=10100111
    @(posedge clk); enc_addr_config = 8'hBA; enc_data_config = 20'h800A8; // 0xBA: len=8, code=10101000
    @(posedge clk); enc_addr_config = 8'hBB; enc_data_config = 20'h800A9; // 0xBB: len=8, code=10101001
    @(posedge clk); enc_addr_config = 8'hBC; enc_data_config = 20'h800AA; // 0xBC: len=8, code=10101010
    @(posedge clk); enc_addr_config = 8'hBD; enc_data_config = 20'h800AB; // 0xBD: len=8, code=10101011
    @(posedge clk); enc_addr_config = 8'hBE; enc_data_config = 20'h800AC; // 0xBE: len=8, code=10101100
    @(posedge clk); enc_addr_config = 8'hBF; enc_data_config = 20'h60005; // 0xBF: len=6, code=000101
    @(posedge clk); enc_addr_config = 8'hC0; enc_data_config = 20'h7000C; // 0xC0: len=7, code=0001100
    @(posedge clk); enc_addr_config = 8'hC1; enc_data_config = 20'h800AD; // 0xC1: len=8, code=10101101
    @(posedge clk); enc_addr_config = 8'hC2; enc_data_config = 20'h800AE; // 0xC2: len=8, code=10101110
    @(posedge clk); enc_addr_config = 8'hC3; enc_data_config = 20'h800AF; // 0xC3: len=8, code=10101111
    @(posedge clk); enc_addr_config = 8'hC4; enc_data_config = 20'h800B0; // 0xC4: len=8, code=10110000
    @(posedge clk); enc_addr_config = 8'hC5; enc_data_config = 20'h800B1; // 0xC5: len=8, code=10110001
    @(posedge clk); enc_addr_config = 8'hC6; enc_data_config = 20'h800B2; // 0xC6: len=8, code=10110010
    @(posedge clk); enc_addr_config = 8'hC7; enc_data_config = 20'h800B3; // 0xC7: len=8, code=10110011
    @(posedge clk); enc_addr_config = 8'hC8; enc_data_config = 20'h800B4; // 0xC8: len=8, code=10110100
    @(posedge clk); enc_addr_config = 8'hC9; enc_data_config = 20'h800B5; // 0xC9: len=8, code=10110101
    @(posedge clk); enc_addr_config = 8'hCA; enc_data_config = 20'h800B6; // 0xCA: len=8, code=10110110
    @(posedge clk); enc_addr_config = 8'hCB; enc_data_config = 20'h800B7; // 0xCB: len=8, code=10110111
    @(posedge clk); enc_addr_config = 8'hCC; enc_data_config = 20'h800B8; // 0xCC: len=8, code=10111000
    @(posedge clk); enc_addr_config = 8'hCD; enc_data_config = 20'h800B9; // 0xCD: len=8, code=10111001
    @(posedge clk); enc_addr_config = 8'hCE; enc_data_config = 20'h800BA; // 0xCE: len=8, code=10111010
    @(posedge clk); enc_addr_config = 8'hCF; enc_data_config = 20'h800BB; // 0xCF: len=8, code=10111011
    @(posedge clk); enc_addr_config = 8'hD0; enc_data_config = 20'h800BC; // 0xD0: len=8, code=10111100
    @(posedge clk); enc_addr_config = 8'hD1; enc_data_config = 20'h800BD; // 0xD1: len=8, code=10111101
    @(posedge clk); enc_addr_config = 8'hD2; enc_data_config = 20'h800BE; // 0xD2: len=8, code=10111110
    @(posedge clk); enc_addr_config = 8'hD3; enc_data_config = 20'h800BF; // 0xD3: len=8, code=10111111
    @(posedge clk); enc_addr_config = 8'hD4; enc_data_config = 20'h800C0; // 0xD4: len=8, code=11000000
    @(posedge clk); enc_addr_config = 8'hD5; enc_data_config = 20'h800C1; // 0xD5: len=8, code=11000001
    @(posedge clk); enc_addr_config = 8'hD6; enc_data_config = 20'h800C2; // 0xD6: len=8, code=11000010
    @(posedge clk); enc_addr_config = 8'hD7; enc_data_config = 20'h800C3; // 0xD7: len=8, code=11000011
    @(posedge clk); enc_addr_config = 8'hD8; enc_data_config = 20'h800C4; // 0xD8: len=8, code=11000100
    @(posedge clk); enc_addr_config = 8'hD9; enc_data_config = 20'h800C5; // 0xD9: len=8, code=11000101
    @(posedge clk); enc_addr_config = 8'hDA; enc_data_config = 20'h800C6; // 0xDA: len=8, code=11000110
    @(posedge clk); enc_addr_config = 8'hDB; enc_data_config = 20'h800C7; // 0xDB: len=8, code=11000111
    @(posedge clk); enc_addr_config = 8'hDC; enc_data_config = 20'h800C8; // 0xDC: len=8, code=11001000
    @(posedge clk); enc_addr_config = 8'hDD; enc_data_config = 20'h800C9; // 0xDD: len=8, code=11001001
    @(posedge clk); enc_addr_config = 8'hDE; enc_data_config = 20'h800CA; // 0xDE: len=8, code=11001010
    @(posedge clk); enc_addr_config = 8'hDF; enc_data_config = 20'h800CB; // 0xDF: len=8, code=11001011
    @(posedge clk); enc_addr_config = 8'hE0; enc_data_config = 20'h800CC; // 0xE0: len=8, code=11001100
    @(posedge clk); enc_addr_config = 8'hE1; enc_data_config = 20'h800CD; // 0xE1: len=8, code=11001101
    @(posedge clk); enc_addr_config = 8'hE2; enc_data_config = 20'h800CE; // 0xE2: len=8, code=11001110
    @(posedge clk); enc_addr_config = 8'hE3; enc_data_config = 20'h800CF; // 0xE3: len=8, code=11001111
    @(posedge clk); enc_addr_config = 8'hE4; enc_data_config = 20'h800D0; // 0xE4: len=8, code=11010000
    @(posedge clk); enc_addr_config = 8'hE5; enc_data_config = 20'h800D1; // 0xE5: len=8, code=11010001
    @(posedge clk); enc_addr_config = 8'hE6; enc_data_config = 20'h800D2; // 0xE6: len=8, code=11010010
    @(posedge clk); enc_addr_config = 8'hE7; enc_data_config = 20'h800D3; // 0xE7: len=8, code=11010011
    @(posedge clk); enc_addr_config = 8'hE8; enc_data_config = 20'h800D4; // 0xE8: len=8, code=11010100
    @(posedge clk); enc_addr_config = 8'hE9; enc_data_config = 20'h800D5; // 0xE9: len=8, code=11010101
    @(posedge clk); enc_addr_config = 8'hEA; enc_data_config = 20'h800D6; // 0xEA: len=8, code=11010110
    @(posedge clk); enc_addr_config = 8'hEB; enc_data_config = 20'h800D7; // 0xEB: len=8, code=11010111
    @(posedge clk); enc_addr_config = 8'hEC; enc_data_config = 20'h800D8; // 0xEC: len=8, code=11011000
    @(posedge clk); enc_addr_config = 8'hED; enc_data_config = 20'h800D9; // 0xED: len=8, code=11011001
    @(posedge clk); enc_addr_config = 8'hEE; enc_data_config = 20'h800DA; // 0xEE: len=8, code=11011010
    @(posedge clk); enc_addr_config = 8'hEF; enc_data_config = 20'h800DB; // 0xEF: len=8, code=11011011
    @(posedge clk); enc_addr_config = 8'hF0; enc_data_config = 20'h800DC; // 0xF0: len=8, code=11011100
    @(posedge clk); enc_addr_config = 8'hF1; enc_data_config = 20'h800DD; // 0xF1: len=8, code=11011101
    @(posedge clk); enc_addr_config = 8'hF2; enc_data_config = 20'h800DE; // 0xF2: len=8, code=11011110
    @(posedge clk); enc_addr_config = 8'hF3; enc_data_config = 20'h800DF; // 0xF3: len=8, code=11011111
    @(posedge clk); enc_addr_config = 8'hF4; enc_data_config = 20'h800E0; // 0xF4: len=8, code=11100000
    @(posedge clk); enc_addr_config = 8'hF5; enc_data_config = 20'h800E1; // 0xF5: len=8, code=11100001
    @(posedge clk); enc_addr_config = 8'hF6; enc_data_config = 20'h800E2; // 0xF6: len=8, code=11100010
    @(posedge clk); enc_addr_config = 8'hF7; enc_data_config = 20'h800E3; // 0xF7: len=8, code=11100011
    @(posedge clk); enc_addr_config = 8'hF8; enc_data_config = 20'h800E4; // 0xF8: len=8, code=11100100
    @(posedge clk); enc_addr_config = 8'hF9; enc_data_config = 20'h800E5; // 0xF9: len=8, code=11100101
    @(posedge clk); enc_addr_config = 8'hFA; enc_data_config = 20'h800E6; // 0xFA: len=8, code=11100110
    @(posedge clk); enc_addr_config = 8'hFB; enc_data_config = 20'h800E7; // 0xFB: len=8, code=11100111
    @(posedge clk); enc_addr_config = 8'hFC; enc_data_config = 20'h800E8; // 0xFC: len=8, code=11101000
    @(posedge clk); enc_addr_config = 8'hFD; enc_data_config = 20'h800E9; // 0xFD: len=8, code=11101001
    @(posedge clk); enc_addr_config = 8'hFE; enc_data_config = 20'h800EA; // 0xFE: len=8, code=11101010
    @(posedge clk); enc_addr_config = 8'hFF; enc_data_config = 20'h800EB; // 0xFF: len=8, code=11101011
    @(posedge clk); enc_wr_en = 0;
end
endtask

task config_decoder_full();
begin
    dec_wr_en = 1;

    // first_code table (table_sel = 0)
    dec_table_sel = 2'd0;
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'hFFFF; // first_code[1]
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'hFFFF; // first_code[2]
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'hFFFF; // first_code[3]
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'hFFFF; // first_code[4]
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'h0000; // first_code[5]
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'h0800; // first_code[6]
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'h1800; // first_code[7]
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'h1A00; // first_code[8]
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'hEC00; // first_code[9]
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'hFFFF; // first_code[10]
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'hFFFF; // first_code[11]
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'hFFFF; // first_code[12]
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'hFFFF; // first_code[13]
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'hFFFF; // first_code[14]
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'hFFFF; // first_code[15]
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'hFFFF; // first_code[16]

    // base table (table_sel = 1)
    dec_table_sel = 2'd1;
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'd0; // base[1]
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'd0; // base[2]
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'd0; // base[3]
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'd0; // base[4]
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'd0; // base[5]
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'd1; // base[6]
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'd5; // base[7]
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'd6; // base[8]
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'd216; // base[9]
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'd256; // base[10]
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'd256; // base[11]
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'd256; // base[12]
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'd256; // base[13]
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'd256; // base[14]
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'd256; // base[15]
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'd256; // base[16]
    @(posedge clk); // extra cycle before table_sel change

    // symbol_table (table_sel = 2)
    dec_table_sel = 2'd2;
    @(posedge clk); dec_addr_config = 8'd0; dec_data_config = 16'h0000; // [0] = 0x00
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'h003F; // [1] = 0x3F
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'h0040; // [2] = 0x40
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'h0080; // [3] = 0x80
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'h00BF; // [4] = 0xBF
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'h00C0; // [5] = 0xC0
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'h0001; // [6] = 0x01
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'h0002; // [7] = 0x02
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'h0003; // [8] = 0x03
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'h0004; // [9] = 0x04
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'h0005; // [10] = 0x05
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'h0006; // [11] = 0x06
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'h0007; // [12] = 0x07
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'h0008; // [13] = 0x08
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'h0009; // [14] = 0x09
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'h000A; // [15] = 0x0A
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'h000B; // [16] = 0x0B
    @(posedge clk); dec_addr_config = 8'd17; dec_data_config = 16'h000C; // [17] = 0x0C
    @(posedge clk); dec_addr_config = 8'd18; dec_data_config = 16'h000D; // [18] = 0x0D
    @(posedge clk); dec_addr_config = 8'd19; dec_data_config = 16'h000E; // [19] = 0x0E
    @(posedge clk); dec_addr_config = 8'd20; dec_data_config = 16'h000F; // [20] = 0x0F
    @(posedge clk); dec_addr_config = 8'd21; dec_data_config = 16'h0038; // [21] = 0x38
    @(posedge clk); dec_addr_config = 8'd22; dec_data_config = 16'h0039; // [22] = 0x39
    @(posedge clk); dec_addr_config = 8'd23; dec_data_config = 16'h003A; // [23] = 0x3A
    @(posedge clk); dec_addr_config = 8'd24; dec_data_config = 16'h003B; // [24] = 0x3B
    @(posedge clk); dec_addr_config = 8'd25; dec_data_config = 16'h003C; // [25] = 0x3C
    @(posedge clk); dec_addr_config = 8'd26; dec_data_config = 16'h003D; // [26] = 0x3D
    @(posedge clk); dec_addr_config = 8'd27; dec_data_config = 16'h003E; // [27] = 0x3E
    @(posedge clk); dec_addr_config = 8'd28; dec_data_config = 16'h0041; // [28] = 0x41
    @(posedge clk); dec_addr_config = 8'd29; dec_data_config = 16'h0042; // [29] = 0x42
    @(posedge clk); dec_addr_config = 8'd30; dec_data_config = 16'h0043; // [30] = 0x43
    @(posedge clk); dec_addr_config = 8'd31; dec_data_config = 16'h0044; // [31] = 0x44
    @(posedge clk); dec_addr_config = 8'd32; dec_data_config = 16'h0045; // [32] = 0x45
    @(posedge clk); dec_addr_config = 8'd33; dec_data_config = 16'h0046; // [33] = 0x46
    @(posedge clk); dec_addr_config = 8'd34; dec_data_config = 16'h0047; // [34] = 0x47
    @(posedge clk); dec_addr_config = 8'd35; dec_data_config = 16'h0048; // [35] = 0x48
    @(posedge clk); dec_addr_config = 8'd36; dec_data_config = 16'h0049; // [36] = 0x49
    @(posedge clk); dec_addr_config = 8'd37; dec_data_config = 16'h004A; // [37] = 0x4A
    @(posedge clk); dec_addr_config = 8'd38; dec_data_config = 16'h004B; // [38] = 0x4B
    @(posedge clk); dec_addr_config = 8'd39; dec_data_config = 16'h004C; // [39] = 0x4C
    @(posedge clk); dec_addr_config = 8'd40; dec_data_config = 16'h004D; // [40] = 0x4D
    @(posedge clk); dec_addr_config = 8'd41; dec_data_config = 16'h004E; // [41] = 0x4E
    @(posedge clk); dec_addr_config = 8'd42; dec_data_config = 16'h004F; // [42] = 0x4F
    @(posedge clk); dec_addr_config = 8'd43; dec_data_config = 16'h0050; // [43] = 0x50
    @(posedge clk); dec_addr_config = 8'd44; dec_data_config = 16'h0051; // [44] = 0x51
    @(posedge clk); dec_addr_config = 8'd45; dec_data_config = 16'h0052; // [45] = 0x52
    @(posedge clk); dec_addr_config = 8'd46; dec_data_config = 16'h0053; // [46] = 0x53
    @(posedge clk); dec_addr_config = 8'd47; dec_data_config = 16'h0054; // [47] = 0x54
    @(posedge clk); dec_addr_config = 8'd48; dec_data_config = 16'h0055; // [48] = 0x55
    @(posedge clk); dec_addr_config = 8'd49; dec_data_config = 16'h0056; // [49] = 0x56
    @(posedge clk); dec_addr_config = 8'd50; dec_data_config = 16'h0057; // [50] = 0x57
    @(posedge clk); dec_addr_config = 8'd51; dec_data_config = 16'h0058; // [51] = 0x58
    @(posedge clk); dec_addr_config = 8'd52; dec_data_config = 16'h0059; // [52] = 0x59
    @(posedge clk); dec_addr_config = 8'd53; dec_data_config = 16'h005A; // [53] = 0x5A
    @(posedge clk); dec_addr_config = 8'd54; dec_data_config = 16'h005B; // [54] = 0x5B
    @(posedge clk); dec_addr_config = 8'd55; dec_data_config = 16'h005C; // [55] = 0x5C
    @(posedge clk); dec_addr_config = 8'd56; dec_data_config = 16'h005D; // [56] = 0x5D
    @(posedge clk); dec_addr_config = 8'd57; dec_data_config = 16'h005E; // [57] = 0x5E
    @(posedge clk); dec_addr_config = 8'd58; dec_data_config = 16'h005F; // [58] = 0x5F
    @(posedge clk); dec_addr_config = 8'd59; dec_data_config = 16'h0060; // [59] = 0x60
    @(posedge clk); dec_addr_config = 8'd60; dec_data_config = 16'h0061; // [60] = 0x61
    @(posedge clk); dec_addr_config = 8'd61; dec_data_config = 16'h0062; // [61] = 0x62
    @(posedge clk); dec_addr_config = 8'd62; dec_data_config = 16'h0063; // [62] = 0x63
    @(posedge clk); dec_addr_config = 8'd63; dec_data_config = 16'h0064; // [63] = 0x64
    @(posedge clk); dec_addr_config = 8'd64; dec_data_config = 16'h0065; // [64] = 0x65
    @(posedge clk); dec_addr_config = 8'd65; dec_data_config = 16'h0066; // [65] = 0x66
    @(posedge clk); dec_addr_config = 8'd66; dec_data_config = 16'h0067; // [66] = 0x67
    @(posedge clk); dec_addr_config = 8'd67; dec_data_config = 16'h0068; // [67] = 0x68
    @(posedge clk); dec_addr_config = 8'd68; dec_data_config = 16'h0069; // [68] = 0x69
    @(posedge clk); dec_addr_config = 8'd69; dec_data_config = 16'h006A; // [69] = 0x6A
    @(posedge clk); dec_addr_config = 8'd70; dec_data_config = 16'h006B; // [70] = 0x6B
    @(posedge clk); dec_addr_config = 8'd71; dec_data_config = 16'h006C; // [71] = 0x6C
    @(posedge clk); dec_addr_config = 8'd72; dec_data_config = 16'h006D; // [72] = 0x6D
    @(posedge clk); dec_addr_config = 8'd73; dec_data_config = 16'h006E; // [73] = 0x6E
    @(posedge clk); dec_addr_config = 8'd74; dec_data_config = 16'h006F; // [74] = 0x6F
    @(posedge clk); dec_addr_config = 8'd75; dec_data_config = 16'h0070; // [75] = 0x70
    @(posedge clk); dec_addr_config = 8'd76; dec_data_config = 16'h0071; // [76] = 0x71
    @(posedge clk); dec_addr_config = 8'd77; dec_data_config = 16'h0072; // [77] = 0x72
    @(posedge clk); dec_addr_config = 8'd78; dec_data_config = 16'h0073; // [78] = 0x73
    @(posedge clk); dec_addr_config = 8'd79; dec_data_config = 16'h0074; // [79] = 0x74
    @(posedge clk); dec_addr_config = 8'd80; dec_data_config = 16'h0075; // [80] = 0x75
    @(posedge clk); dec_addr_config = 8'd81; dec_data_config = 16'h0076; // [81] = 0x76
    @(posedge clk); dec_addr_config = 8'd82; dec_data_config = 16'h0077; // [82] = 0x77
    @(posedge clk); dec_addr_config = 8'd83; dec_data_config = 16'h0078; // [83] = 0x78
    @(posedge clk); dec_addr_config = 8'd84; dec_data_config = 16'h0079; // [84] = 0x79
    @(posedge clk); dec_addr_config = 8'd85; dec_data_config = 16'h007A; // [85] = 0x7A
    @(posedge clk); dec_addr_config = 8'd86; dec_data_config = 16'h007B; // [86] = 0x7B
    @(posedge clk); dec_addr_config = 8'd87; dec_data_config = 16'h007C; // [87] = 0x7C
    @(posedge clk); dec_addr_config = 8'd88; dec_data_config = 16'h007D; // [88] = 0x7D
    @(posedge clk); dec_addr_config = 8'd89; dec_data_config = 16'h007E; // [89] = 0x7E
    @(posedge clk); dec_addr_config = 8'd90; dec_data_config = 16'h007F; // [90] = 0x7F
    @(posedge clk); dec_addr_config = 8'd91; dec_data_config = 16'h0081; // [91] = 0x81
    @(posedge clk); dec_addr_config = 8'd92; dec_data_config = 16'h0082; // [92] = 0x82
    @(posedge clk); dec_addr_config = 8'd93; dec_data_config = 16'h0083; // [93] = 0x83
    @(posedge clk); dec_addr_config = 8'd94; dec_data_config = 16'h0084; // [94] = 0x84
    @(posedge clk); dec_addr_config = 8'd95; dec_data_config = 16'h0085; // [95] = 0x85
    @(posedge clk); dec_addr_config = 8'd96; dec_data_config = 16'h0086; // [96] = 0x86
    @(posedge clk); dec_addr_config = 8'd97; dec_data_config = 16'h0087; // [97] = 0x87
    @(posedge clk); dec_addr_config = 8'd98; dec_data_config = 16'h0088; // [98] = 0x88
    @(posedge clk); dec_addr_config = 8'd99; dec_data_config = 16'h0089; // [99] = 0x89
    @(posedge clk); dec_addr_config = 8'd100; dec_data_config = 16'h008A; // [100] = 0x8A
    @(posedge clk); dec_addr_config = 8'd101; dec_data_config = 16'h008B; // [101] = 0x8B
    @(posedge clk); dec_addr_config = 8'd102; dec_data_config = 16'h008C; // [102] = 0x8C
    @(posedge clk); dec_addr_config = 8'd103; dec_data_config = 16'h008D; // [103] = 0x8D
    @(posedge clk); dec_addr_config = 8'd104; dec_data_config = 16'h008E; // [104] = 0x8E
    @(posedge clk); dec_addr_config = 8'd105; dec_data_config = 16'h008F; // [105] = 0x8F
    @(posedge clk); dec_addr_config = 8'd106; dec_data_config = 16'h0090; // [106] = 0x90
    @(posedge clk); dec_addr_config = 8'd107; dec_data_config = 16'h0091; // [107] = 0x91
    @(posedge clk); dec_addr_config = 8'd108; dec_data_config = 16'h0092; // [108] = 0x92
    @(posedge clk); dec_addr_config = 8'd109; dec_data_config = 16'h0093; // [109] = 0x93
    @(posedge clk); dec_addr_config = 8'd110; dec_data_config = 16'h0094; // [110] = 0x94
    @(posedge clk); dec_addr_config = 8'd111; dec_data_config = 16'h0095; // [111] = 0x95
    @(posedge clk); dec_addr_config = 8'd112; dec_data_config = 16'h0096; // [112] = 0x96
    @(posedge clk); dec_addr_config = 8'd113; dec_data_config = 16'h0097; // [113] = 0x97
    @(posedge clk); dec_addr_config = 8'd114; dec_data_config = 16'h0098; // [114] = 0x98
    @(posedge clk); dec_addr_config = 8'd115; dec_data_config = 16'h0099; // [115] = 0x99
    @(posedge clk); dec_addr_config = 8'd116; dec_data_config = 16'h009A; // [116] = 0x9A
    @(posedge clk); dec_addr_config = 8'd117; dec_data_config = 16'h009B; // [117] = 0x9B
    @(posedge clk); dec_addr_config = 8'd118; dec_data_config = 16'h009C; // [118] = 0x9C
    @(posedge clk); dec_addr_config = 8'd119; dec_data_config = 16'h009D; // [119] = 0x9D
    @(posedge clk); dec_addr_config = 8'd120; dec_data_config = 16'h009E; // [120] = 0x9E
    @(posedge clk); dec_addr_config = 8'd121; dec_data_config = 16'h009F; // [121] = 0x9F
    @(posedge clk); dec_addr_config = 8'd122; dec_data_config = 16'h00A0; // [122] = 0xA0
    @(posedge clk); dec_addr_config = 8'd123; dec_data_config = 16'h00A1; // [123] = 0xA1
    @(posedge clk); dec_addr_config = 8'd124; dec_data_config = 16'h00A2; // [124] = 0xA2
    @(posedge clk); dec_addr_config = 8'd125; dec_data_config = 16'h00A3; // [125] = 0xA3
    @(posedge clk); dec_addr_config = 8'd126; dec_data_config = 16'h00A4; // [126] = 0xA4
    @(posedge clk); dec_addr_config = 8'd127; dec_data_config = 16'h00A5; // [127] = 0xA5
    @(posedge clk); dec_addr_config = 8'd128; dec_data_config = 16'h00A6; // [128] = 0xA6
    @(posedge clk); dec_addr_config = 8'd129; dec_data_config = 16'h00A7; // [129] = 0xA7
    @(posedge clk); dec_addr_config = 8'd130; dec_data_config = 16'h00A8; // [130] = 0xA8
    @(posedge clk); dec_addr_config = 8'd131; dec_data_config = 16'h00A9; // [131] = 0xA9
    @(posedge clk); dec_addr_config = 8'd132; dec_data_config = 16'h00AA; // [132] = 0xAA
    @(posedge clk); dec_addr_config = 8'd133; dec_data_config = 16'h00AB; // [133] = 0xAB
    @(posedge clk); dec_addr_config = 8'd134; dec_data_config = 16'h00AC; // [134] = 0xAC
    @(posedge clk); dec_addr_config = 8'd135; dec_data_config = 16'h00AD; // [135] = 0xAD
    @(posedge clk); dec_addr_config = 8'd136; dec_data_config = 16'h00AE; // [136] = 0xAE
    @(posedge clk); dec_addr_config = 8'd137; dec_data_config = 16'h00AF; // [137] = 0xAF
    @(posedge clk); dec_addr_config = 8'd138; dec_data_config = 16'h00B0; // [138] = 0xB0
    @(posedge clk); dec_addr_config = 8'd139; dec_data_config = 16'h00B1; // [139] = 0xB1
    @(posedge clk); dec_addr_config = 8'd140; dec_data_config = 16'h00B2; // [140] = 0xB2
    @(posedge clk); dec_addr_config = 8'd141; dec_data_config = 16'h00B3; // [141] = 0xB3
    @(posedge clk); dec_addr_config = 8'd142; dec_data_config = 16'h00B4; // [142] = 0xB4
    @(posedge clk); dec_addr_config = 8'd143; dec_data_config = 16'h00B5; // [143] = 0xB5
    @(posedge clk); dec_addr_config = 8'd144; dec_data_config = 16'h00B6; // [144] = 0xB6
    @(posedge clk); dec_addr_config = 8'd145; dec_data_config = 16'h00B7; // [145] = 0xB7
    @(posedge clk); dec_addr_config = 8'd146; dec_data_config = 16'h00B8; // [146] = 0xB8
    @(posedge clk); dec_addr_config = 8'd147; dec_data_config = 16'h00B9; // [147] = 0xB9
    @(posedge clk); dec_addr_config = 8'd148; dec_data_config = 16'h00BA; // [148] = 0xBA
    @(posedge clk); dec_addr_config = 8'd149; dec_data_config = 16'h00BB; // [149] = 0xBB
    @(posedge clk); dec_addr_config = 8'd150; dec_data_config = 16'h00BC; // [150] = 0xBC
    @(posedge clk); dec_addr_config = 8'd151; dec_data_config = 16'h00BD; // [151] = 0xBD
    @(posedge clk); dec_addr_config = 8'd152; dec_data_config = 16'h00BE; // [152] = 0xBE
    @(posedge clk); dec_addr_config = 8'd153; dec_data_config = 16'h00C1; // [153] = 0xC1
    @(posedge clk); dec_addr_config = 8'd154; dec_data_config = 16'h00C2; // [154] = 0xC2
    @(posedge clk); dec_addr_config = 8'd155; dec_data_config = 16'h00C3; // [155] = 0xC3
    @(posedge clk); dec_addr_config = 8'd156; dec_data_config = 16'h00C4; // [156] = 0xC4
    @(posedge clk); dec_addr_config = 8'd157; dec_data_config = 16'h00C5; // [157] = 0xC5
    @(posedge clk); dec_addr_config = 8'd158; dec_data_config = 16'h00C6; // [158] = 0xC6
    @(posedge clk); dec_addr_config = 8'd159; dec_data_config = 16'h00C7; // [159] = 0xC7
    @(posedge clk); dec_addr_config = 8'd160; dec_data_config = 16'h00C8; // [160] = 0xC8
    @(posedge clk); dec_addr_config = 8'd161; dec_data_config = 16'h00C9; // [161] = 0xC9
    @(posedge clk); dec_addr_config = 8'd162; dec_data_config = 16'h00CA; // [162] = 0xCA
    @(posedge clk); dec_addr_config = 8'd163; dec_data_config = 16'h00CB; // [163] = 0xCB
    @(posedge clk); dec_addr_config = 8'd164; dec_data_config = 16'h00CC; // [164] = 0xCC
    @(posedge clk); dec_addr_config = 8'd165; dec_data_config = 16'h00CD; // [165] = 0xCD
    @(posedge clk); dec_addr_config = 8'd166; dec_data_config = 16'h00CE; // [166] = 0xCE
    @(posedge clk); dec_addr_config = 8'd167; dec_data_config = 16'h00CF; // [167] = 0xCF
    @(posedge clk); dec_addr_config = 8'd168; dec_data_config = 16'h00D0; // [168] = 0xD0
    @(posedge clk); dec_addr_config = 8'd169; dec_data_config = 16'h00D1; // [169] = 0xD1
    @(posedge clk); dec_addr_config = 8'd170; dec_data_config = 16'h00D2; // [170] = 0xD2
    @(posedge clk); dec_addr_config = 8'd171; dec_data_config = 16'h00D3; // [171] = 0xD3
    @(posedge clk); dec_addr_config = 8'd172; dec_data_config = 16'h00D4; // [172] = 0xD4
    @(posedge clk); dec_addr_config = 8'd173; dec_data_config = 16'h00D5; // [173] = 0xD5
    @(posedge clk); dec_addr_config = 8'd174; dec_data_config = 16'h00D6; // [174] = 0xD6
    @(posedge clk); dec_addr_config = 8'd175; dec_data_config = 16'h00D7; // [175] = 0xD7
    @(posedge clk); dec_addr_config = 8'd176; dec_data_config = 16'h00D8; // [176] = 0xD8
    @(posedge clk); dec_addr_config = 8'd177; dec_data_config = 16'h00D9; // [177] = 0xD9
    @(posedge clk); dec_addr_config = 8'd178; dec_data_config = 16'h00DA; // [178] = 0xDA
    @(posedge clk); dec_addr_config = 8'd179; dec_data_config = 16'h00DB; // [179] = 0xDB
    @(posedge clk); dec_addr_config = 8'd180; dec_data_config = 16'h00DC; // [180] = 0xDC
    @(posedge clk); dec_addr_config = 8'd181; dec_data_config = 16'h00DD; // [181] = 0xDD
    @(posedge clk); dec_addr_config = 8'd182; dec_data_config = 16'h00DE; // [182] = 0xDE
    @(posedge clk); dec_addr_config = 8'd183; dec_data_config = 16'h00DF; // [183] = 0xDF
    @(posedge clk); dec_addr_config = 8'd184; dec_data_config = 16'h00E0; // [184] = 0xE0
    @(posedge clk); dec_addr_config = 8'd185; dec_data_config = 16'h00E1; // [185] = 0xE1
    @(posedge clk); dec_addr_config = 8'd186; dec_data_config = 16'h00E2; // [186] = 0xE2
    @(posedge clk); dec_addr_config = 8'd187; dec_data_config = 16'h00E3; // [187] = 0xE3
    @(posedge clk); dec_addr_config = 8'd188; dec_data_config = 16'h00E4; // [188] = 0xE4
    @(posedge clk); dec_addr_config = 8'd189; dec_data_config = 16'h00E5; // [189] = 0xE5
    @(posedge clk); dec_addr_config = 8'd190; dec_data_config = 16'h00E6; // [190] = 0xE6
    @(posedge clk); dec_addr_config = 8'd191; dec_data_config = 16'h00E7; // [191] = 0xE7
    @(posedge clk); dec_addr_config = 8'd192; dec_data_config = 16'h00E8; // [192] = 0xE8
    @(posedge clk); dec_addr_config = 8'd193; dec_data_config = 16'h00E9; // [193] = 0xE9
    @(posedge clk); dec_addr_config = 8'd194; dec_data_config = 16'h00EA; // [194] = 0xEA
    @(posedge clk); dec_addr_config = 8'd195; dec_data_config = 16'h00EB; // [195] = 0xEB
    @(posedge clk); dec_addr_config = 8'd196; dec_data_config = 16'h00EC; // [196] = 0xEC
    @(posedge clk); dec_addr_config = 8'd197; dec_data_config = 16'h00ED; // [197] = 0xED
    @(posedge clk); dec_addr_config = 8'd198; dec_data_config = 16'h00EE; // [198] = 0xEE
    @(posedge clk); dec_addr_config = 8'd199; dec_data_config = 16'h00EF; // [199] = 0xEF
    @(posedge clk); dec_addr_config = 8'd200; dec_data_config = 16'h00F0; // [200] = 0xF0
    @(posedge clk); dec_addr_config = 8'd201; dec_data_config = 16'h00F1; // [201] = 0xF1
    @(posedge clk); dec_addr_config = 8'd202; dec_data_config = 16'h00F2; // [202] = 0xF2
    @(posedge clk); dec_addr_config = 8'd203; dec_data_config = 16'h00F3; // [203] = 0xF3
    @(posedge clk); dec_addr_config = 8'd204; dec_data_config = 16'h00F4; // [204] = 0xF4
    @(posedge clk); dec_addr_config = 8'd205; dec_data_config = 16'h00F5; // [205] = 0xF5
    @(posedge clk); dec_addr_config = 8'd206; dec_data_config = 16'h00F6; // [206] = 0xF6
    @(posedge clk); dec_addr_config = 8'd207; dec_data_config = 16'h00F7; // [207] = 0xF7
    @(posedge clk); dec_addr_config = 8'd208; dec_data_config = 16'h00F8; // [208] = 0xF8
    @(posedge clk); dec_addr_config = 8'd209; dec_data_config = 16'h00F9; // [209] = 0xF9
    @(posedge clk); dec_addr_config = 8'd210; dec_data_config = 16'h00FA; // [210] = 0xFA
    @(posedge clk); dec_addr_config = 8'd211; dec_data_config = 16'h00FB; // [211] = 0xFB
    @(posedge clk); dec_addr_config = 8'd212; dec_data_config = 16'h00FC; // [212] = 0xFC
    @(posedge clk); dec_addr_config = 8'd213; dec_data_config = 16'h00FD; // [213] = 0xFD
    @(posedge clk); dec_addr_config = 8'd214; dec_data_config = 16'h00FE; // [214] = 0xFE
    @(posedge clk); dec_addr_config = 8'd215; dec_data_config = 16'h00FF; // [215] = 0xFF
    @(posedge clk); dec_addr_config = 8'd216; dec_data_config = 16'h0010; // [216] = 0x10
    @(posedge clk); dec_addr_config = 8'd217; dec_data_config = 16'h0011; // [217] = 0x11
    @(posedge clk); dec_addr_config = 8'd218; dec_data_config = 16'h0012; // [218] = 0x12
    @(posedge clk); dec_addr_config = 8'd219; dec_data_config = 16'h0013; // [219] = 0x13
    @(posedge clk); dec_addr_config = 8'd220; dec_data_config = 16'h0014; // [220] = 0x14
    @(posedge clk); dec_addr_config = 8'd221; dec_data_config = 16'h0015; // [221] = 0x15
    @(posedge clk); dec_addr_config = 8'd222; dec_data_config = 16'h0016; // [222] = 0x16
    @(posedge clk); dec_addr_config = 8'd223; dec_data_config = 16'h0017; // [223] = 0x17
    @(posedge clk); dec_addr_config = 8'd224; dec_data_config = 16'h0018; // [224] = 0x18
    @(posedge clk); dec_addr_config = 8'd225; dec_data_config = 16'h0019; // [225] = 0x19
    @(posedge clk); dec_addr_config = 8'd226; dec_data_config = 16'h001A; // [226] = 0x1A
    @(posedge clk); dec_addr_config = 8'd227; dec_data_config = 16'h001B; // [227] = 0x1B
    @(posedge clk); dec_addr_config = 8'd228; dec_data_config = 16'h001C; // [228] = 0x1C
    @(posedge clk); dec_addr_config = 8'd229; dec_data_config = 16'h001D; // [229] = 0x1D
    @(posedge clk); dec_addr_config = 8'd230; dec_data_config = 16'h001E; // [230] = 0x1E
    @(posedge clk); dec_addr_config = 8'd231; dec_data_config = 16'h001F; // [231] = 0x1F
    @(posedge clk); dec_addr_config = 8'd232; dec_data_config = 16'h0020; // [232] = 0x20
    @(posedge clk); dec_addr_config = 8'd233; dec_data_config = 16'h0021; // [233] = 0x21
    @(posedge clk); dec_addr_config = 8'd234; dec_data_config = 16'h0022; // [234] = 0x22
    @(posedge clk); dec_addr_config = 8'd235; dec_data_config = 16'h0023; // [235] = 0x23
    @(posedge clk); dec_addr_config = 8'd236; dec_data_config = 16'h0024; // [236] = 0x24
    @(posedge clk); dec_addr_config = 8'd237; dec_data_config = 16'h0025; // [237] = 0x25
    @(posedge clk); dec_addr_config = 8'd238; dec_data_config = 16'h0026; // [238] = 0x26
    @(posedge clk); dec_addr_config = 8'd239; dec_data_config = 16'h0027; // [239] = 0x27
    @(posedge clk); dec_addr_config = 8'd240; dec_data_config = 16'h0028; // [240] = 0x28
    @(posedge clk); dec_addr_config = 8'd241; dec_data_config = 16'h0029; // [241] = 0x29
    @(posedge clk); dec_addr_config = 8'd242; dec_data_config = 16'h002A; // [242] = 0x2A
    @(posedge clk); dec_addr_config = 8'd243; dec_data_config = 16'h002B; // [243] = 0x2B
    @(posedge clk); dec_addr_config = 8'd244; dec_data_config = 16'h002C; // [244] = 0x2C
    @(posedge clk); dec_addr_config = 8'd245; dec_data_config = 16'h002D; // [245] = 0x2D
    @(posedge clk); dec_addr_config = 8'd246; dec_data_config = 16'h002E; // [246] = 0x2E
    @(posedge clk); dec_addr_config = 8'd247; dec_data_config = 16'h002F; // [247] = 0x2F
    @(posedge clk); dec_addr_config = 8'd248; dec_data_config = 16'h0030; // [248] = 0x30
    @(posedge clk); dec_addr_config = 8'd249; dec_data_config = 16'h0031; // [249] = 0x31
    @(posedge clk); dec_addr_config = 8'd250; dec_data_config = 16'h0032; // [250] = 0x32
    @(posedge clk); dec_addr_config = 8'd251; dec_data_config = 16'h0033; // [251] = 0x33
    @(posedge clk); dec_addr_config = 8'd252; dec_data_config = 16'h0034; // [252] = 0x34
    @(posedge clk); dec_addr_config = 8'd253; dec_data_config = 16'h0035; // [253] = 0x35
    @(posedge clk); dec_addr_config = 8'd254; dec_data_config = 16'h0036; // [254] = 0x36
    @(posedge clk); dec_addr_config = 8'd255; dec_data_config = 16'h0037; // [255] = 0x37

    @(posedge clk); dec_wr_en = 0;
end
endtask

