// ================================================================
// huffman_tables.svh
// Auto-generated by compute_huffman.py — DO NOT EDIT MANUALLY
//
// Distribution : gradient-like (256-byte alphabet)
// Avg code len : 3.314 bits  (raw = 8 bits)
// Compression  : 2.41x
// ================================================================

task config_encoder_full();
begin
    enc_wr_en = 1;
    @(posedge clk); enc_addr_config = 8'h00; enc_data_config = 20'h10000; // 0x00: len=1, code=0
    @(posedge clk); enc_addr_config = 8'h01; enc_data_config = 20'h800B8; // 0x01: len=8, code=10111000
    @(posedge clk); enc_addr_config = 8'h02; enc_data_config = 20'h800B9; // 0x02: len=8, code=10111001
    @(posedge clk); enc_addr_config = 8'h03; enc_data_config = 20'h800BA; // 0x03: len=8, code=10111010
    @(posedge clk); enc_addr_config = 8'h04; enc_data_config = 20'h800BB; // 0x04: len=8, code=10111011
    @(posedge clk); enc_addr_config = 8'h05; enc_data_config = 20'h800BC; // 0x05: len=8, code=10111100
    @(posedge clk); enc_addr_config = 8'h06; enc_data_config = 20'h800BD; // 0x06: len=8, code=10111101
    @(posedge clk); enc_addr_config = 8'h07; enc_data_config = 20'h800BE; // 0x07: len=8, code=10111110
    @(posedge clk); enc_addr_config = 8'h08; enc_data_config = 20'h800BF; // 0x08: len=8, code=10111111
    @(posedge clk); enc_addr_config = 8'h09; enc_data_config = 20'h800C0; // 0x09: len=8, code=11000000
    @(posedge clk); enc_addr_config = 8'h0A; enc_data_config = 20'h800C1; // 0x0A: len=8, code=11000001
    @(posedge clk); enc_addr_config = 8'h0B; enc_data_config = 20'h800C2; // 0x0B: len=8, code=11000010
    @(posedge clk); enc_addr_config = 8'h0C; enc_data_config = 20'h800C3; // 0x0C: len=8, code=11000011
    @(posedge clk); enc_addr_config = 8'h0D; enc_data_config = 20'h800C4; // 0x0D: len=8, code=11000100
    @(posedge clk); enc_addr_config = 8'h0E; enc_data_config = 20'h800C5; // 0x0E: len=8, code=11000101
    @(posedge clk); enc_addr_config = 8'h0F; enc_data_config = 20'h800C6; // 0x0F: len=8, code=11000110
    @(posedge clk); enc_addr_config = 8'h10; enc_data_config = 20'hB07F0; // 0x10: len=11, code=11111110000
    @(posedge clk); enc_addr_config = 8'h11; enc_data_config = 20'hB07F1; // 0x11: len=11, code=11111110001
    @(posedge clk); enc_addr_config = 8'h12; enc_data_config = 20'hB07F2; // 0x12: len=11, code=11111110010
    @(posedge clk); enc_addr_config = 8'h13; enc_data_config = 20'hB07F3; // 0x13: len=11, code=11111110011
    @(posedge clk); enc_addr_config = 8'h14; enc_data_config = 20'hB07F4; // 0x14: len=11, code=11111110100
    @(posedge clk); enc_addr_config = 8'h15; enc_data_config = 20'hB07F5; // 0x15: len=11, code=11111110101
    @(posedge clk); enc_addr_config = 8'h16; enc_data_config = 20'hB07F6; // 0x16: len=11, code=11111110110
    @(posedge clk); enc_addr_config = 8'h17; enc_data_config = 20'hB07F7; // 0x17: len=11, code=11111110111
    @(posedge clk); enc_addr_config = 8'h18; enc_data_config = 20'hB07F8; // 0x18: len=11, code=11111111000
    @(posedge clk); enc_addr_config = 8'h19; enc_data_config = 20'hB07F9; // 0x19: len=11, code=11111111001
    @(posedge clk); enc_addr_config = 8'h1A; enc_data_config = 20'hB07FA; // 0x1A: len=11, code=11111111010
    @(posedge clk); enc_addr_config = 8'h1B; enc_data_config = 20'hB07FB; // 0x1B: len=11, code=11111111011
    @(posedge clk); enc_addr_config = 8'h1C; enc_data_config = 20'hB07FC; // 0x1C: len=11, code=11111111100
    @(posedge clk); enc_addr_config = 8'h1D; enc_data_config = 20'hB07FD; // 0x1D: len=11, code=11111111101
    @(posedge clk); enc_addr_config = 8'h1E; enc_data_config = 20'hB07FE; // 0x1E: len=11, code=11111111110
    @(posedge clk); enc_addr_config = 8'h1F; enc_data_config = 20'hB07FF; // 0x1F: len=11, code=11111111111
    @(posedge clk); enc_addr_config = 8'h20; enc_data_config = 20'hA031E; // 0x20: len=10, code=1100011110
    @(posedge clk); enc_addr_config = 8'h21; enc_data_config = 20'hA031F; // 0x21: len=10, code=1100011111
    @(posedge clk); enc_addr_config = 8'h22; enc_data_config = 20'hA0320; // 0x22: len=10, code=1100100000
    @(posedge clk); enc_addr_config = 8'h23; enc_data_config = 20'hA0321; // 0x23: len=10, code=1100100001
    @(posedge clk); enc_addr_config = 8'h24; enc_data_config = 20'hA0322; // 0x24: len=10, code=1100100010
    @(posedge clk); enc_addr_config = 8'h25; enc_data_config = 20'hA0323; // 0x25: len=10, code=1100100011
    @(posedge clk); enc_addr_config = 8'h26; enc_data_config = 20'hA0324; // 0x26: len=10, code=1100100100
    @(posedge clk); enc_addr_config = 8'h27; enc_data_config = 20'hA0325; // 0x27: len=10, code=1100100101
    @(posedge clk); enc_addr_config = 8'h28; enc_data_config = 20'hA0326; // 0x28: len=10, code=1100100110
    @(posedge clk); enc_addr_config = 8'h29; enc_data_config = 20'hA0327; // 0x29: len=10, code=1100100111
    @(posedge clk); enc_addr_config = 8'h2A; enc_data_config = 20'hA0328; // 0x2A: len=10, code=1100101000
    @(posedge clk); enc_addr_config = 8'h2B; enc_data_config = 20'hA0329; // 0x2B: len=10, code=1100101001
    @(posedge clk); enc_addr_config = 8'h2C; enc_data_config = 20'hA032A; // 0x2C: len=10, code=1100101010
    @(posedge clk); enc_addr_config = 8'h2D; enc_data_config = 20'hA032B; // 0x2D: len=10, code=1100101011
    @(posedge clk); enc_addr_config = 8'h2E; enc_data_config = 20'hA032C; // 0x2E: len=10, code=1100101100
    @(posedge clk); enc_addr_config = 8'h2F; enc_data_config = 20'hA032D; // 0x2F: len=10, code=1100101101
    @(posedge clk); enc_addr_config = 8'h30; enc_data_config = 20'hA032E; // 0x30: len=10, code=1100101110
    @(posedge clk); enc_addr_config = 8'h31; enc_data_config = 20'hA032F; // 0x31: len=10, code=1100101111
    @(posedge clk); enc_addr_config = 8'h32; enc_data_config = 20'hA0330; // 0x32: len=10, code=1100110000
    @(posedge clk); enc_addr_config = 8'h33; enc_data_config = 20'hA0331; // 0x33: len=10, code=1100110001
    @(posedge clk); enc_addr_config = 8'h34; enc_data_config = 20'hA0332; // 0x34: len=10, code=1100110010
    @(posedge clk); enc_addr_config = 8'h35; enc_data_config = 20'hA0333; // 0x35: len=10, code=1100110011
    @(posedge clk); enc_addr_config = 8'h36; enc_data_config = 20'hA0334; // 0x36: len=10, code=1100110100
    @(posedge clk); enc_addr_config = 8'h37; enc_data_config = 20'hA0335; // 0x37: len=10, code=1100110101
    @(posedge clk); enc_addr_config = 8'h38; enc_data_config = 20'hA0336; // 0x38: len=10, code=1100110110
    @(posedge clk); enc_addr_config = 8'h39; enc_data_config = 20'hA0337; // 0x39: len=10, code=1100110111
    @(posedge clk); enc_addr_config = 8'h3A; enc_data_config = 20'hA0338; // 0x3A: len=10, code=1100111000
    @(posedge clk); enc_addr_config = 8'h3B; enc_data_config = 20'hA0339; // 0x3B: len=10, code=1100111001
    @(posedge clk); enc_addr_config = 8'h3C; enc_data_config = 20'hA033A; // 0x3C: len=10, code=1100111010
    @(posedge clk); enc_addr_config = 8'h3D; enc_data_config = 20'hA033B; // 0x3D: len=10, code=1100111011
    @(posedge clk); enc_addr_config = 8'h3E; enc_data_config = 20'hA033C; // 0x3E: len=10, code=1100111100
    @(posedge clk); enc_addr_config = 8'h3F; enc_data_config = 20'h40008; // 0x3F: len=4, code=1000
    @(posedge clk); enc_addr_config = 8'h40; enc_data_config = 20'h50014; // 0x40: len=5, code=10100
    @(posedge clk); enc_addr_config = 8'h41; enc_data_config = 20'hA033D; // 0x41: len=10, code=1100111101
    @(posedge clk); enc_addr_config = 8'h42; enc_data_config = 20'hA033E; // 0x42: len=10, code=1100111110
    @(posedge clk); enc_addr_config = 8'h43; enc_data_config = 20'hA033F; // 0x43: len=10, code=1100111111
    @(posedge clk); enc_addr_config = 8'h44; enc_data_config = 20'hA0340; // 0x44: len=10, code=1101000000
    @(posedge clk); enc_addr_config = 8'h45; enc_data_config = 20'hA0341; // 0x45: len=10, code=1101000001
    @(posedge clk); enc_addr_config = 8'h46; enc_data_config = 20'hA0342; // 0x46: len=10, code=1101000010
    @(posedge clk); enc_addr_config = 8'h47; enc_data_config = 20'hA0343; // 0x47: len=10, code=1101000011
    @(posedge clk); enc_addr_config = 8'h48; enc_data_config = 20'hA0344; // 0x48: len=10, code=1101000100
    @(posedge clk); enc_addr_config = 8'h49; enc_data_config = 20'hA0345; // 0x49: len=10, code=1101000101
    @(posedge clk); enc_addr_config = 8'h4A; enc_data_config = 20'hA0346; // 0x4A: len=10, code=1101000110
    @(posedge clk); enc_addr_config = 8'h4B; enc_data_config = 20'hA0347; // 0x4B: len=10, code=1101000111
    @(posedge clk); enc_addr_config = 8'h4C; enc_data_config = 20'hA0348; // 0x4C: len=10, code=1101001000
    @(posedge clk); enc_addr_config = 8'h4D; enc_data_config = 20'hA0349; // 0x4D: len=10, code=1101001001
    @(posedge clk); enc_addr_config = 8'h4E; enc_data_config = 20'hA034A; // 0x4E: len=10, code=1101001010
    @(posedge clk); enc_addr_config = 8'h4F; enc_data_config = 20'hA034B; // 0x4F: len=10, code=1101001011
    @(posedge clk); enc_addr_config = 8'h50; enc_data_config = 20'hA034C; // 0x50: len=10, code=1101001100
    @(posedge clk); enc_addr_config = 8'h51; enc_data_config = 20'hA034D; // 0x51: len=10, code=1101001101
    @(posedge clk); enc_addr_config = 8'h52; enc_data_config = 20'hA034E; // 0x52: len=10, code=1101001110
    @(posedge clk); enc_addr_config = 8'h53; enc_data_config = 20'hA034F; // 0x53: len=10, code=1101001111
    @(posedge clk); enc_addr_config = 8'h54; enc_data_config = 20'hA0350; // 0x54: len=10, code=1101010000
    @(posedge clk); enc_addr_config = 8'h55; enc_data_config = 20'hA0351; // 0x55: len=10, code=1101010001
    @(posedge clk); enc_addr_config = 8'h56; enc_data_config = 20'hA0352; // 0x56: len=10, code=1101010010
    @(posedge clk); enc_addr_config = 8'h57; enc_data_config = 20'hA0353; // 0x57: len=10, code=1101010011
    @(posedge clk); enc_addr_config = 8'h58; enc_data_config = 20'hA0354; // 0x58: len=10, code=1101010100
    @(posedge clk); enc_addr_config = 8'h59; enc_data_config = 20'hA0355; // 0x59: len=10, code=1101010101
    @(posedge clk); enc_addr_config = 8'h5A; enc_data_config = 20'hA0356; // 0x5A: len=10, code=1101010110
    @(posedge clk); enc_addr_config = 8'h5B; enc_data_config = 20'hA0357; // 0x5B: len=10, code=1101010111
    @(posedge clk); enc_addr_config = 8'h5C; enc_data_config = 20'hA0358; // 0x5C: len=10, code=1101011000
    @(posedge clk); enc_addr_config = 8'h5D; enc_data_config = 20'hA0359; // 0x5D: len=10, code=1101011001
    @(posedge clk); enc_addr_config = 8'h5E; enc_data_config = 20'hA035A; // 0x5E: len=10, code=1101011010
    @(posedge clk); enc_addr_config = 8'h5F; enc_data_config = 20'hA035B; // 0x5F: len=10, code=1101011011
    @(posedge clk); enc_addr_config = 8'h60; enc_data_config = 20'hA035C; // 0x60: len=10, code=1101011100
    @(posedge clk); enc_addr_config = 8'h61; enc_data_config = 20'hA035D; // 0x61: len=10, code=1101011101
    @(posedge clk); enc_addr_config = 8'h62; enc_data_config = 20'hA035E; // 0x62: len=10, code=1101011110
    @(posedge clk); enc_addr_config = 8'h63; enc_data_config = 20'hA035F; // 0x63: len=10, code=1101011111
    @(posedge clk); enc_addr_config = 8'h64; enc_data_config = 20'hA0360; // 0x64: len=10, code=1101100000
    @(posedge clk); enc_addr_config = 8'h65; enc_data_config = 20'hA0361; // 0x65: len=10, code=1101100001
    @(posedge clk); enc_addr_config = 8'h66; enc_data_config = 20'hA0362; // 0x66: len=10, code=1101100010
    @(posedge clk); enc_addr_config = 8'h67; enc_data_config = 20'hA0363; // 0x67: len=10, code=1101100011
    @(posedge clk); enc_addr_config = 8'h68; enc_data_config = 20'hA0364; // 0x68: len=10, code=1101100100
    @(posedge clk); enc_addr_config = 8'h69; enc_data_config = 20'hA0365; // 0x69: len=10, code=1101100101
    @(posedge clk); enc_addr_config = 8'h6A; enc_data_config = 20'hA0366; // 0x6A: len=10, code=1101100110
    @(posedge clk); enc_addr_config = 8'h6B; enc_data_config = 20'hA0367; // 0x6B: len=10, code=1101100111
    @(posedge clk); enc_addr_config = 8'h6C; enc_data_config = 20'hA0368; // 0x6C: len=10, code=1101101000
    @(posedge clk); enc_addr_config = 8'h6D; enc_data_config = 20'hA0369; // 0x6D: len=10, code=1101101001
    @(posedge clk); enc_addr_config = 8'h6E; enc_data_config = 20'hA036A; // 0x6E: len=10, code=1101101010
    @(posedge clk); enc_addr_config = 8'h6F; enc_data_config = 20'hA036B; // 0x6F: len=10, code=1101101011
    @(posedge clk); enc_addr_config = 8'h70; enc_data_config = 20'hA036C; // 0x70: len=10, code=1101101100
    @(posedge clk); enc_addr_config = 8'h71; enc_data_config = 20'hA036D; // 0x71: len=10, code=1101101101
    @(posedge clk); enc_addr_config = 8'h72; enc_data_config = 20'hA036E; // 0x72: len=10, code=1101101110
    @(posedge clk); enc_addr_config = 8'h73; enc_data_config = 20'hA036F; // 0x73: len=10, code=1101101111
    @(posedge clk); enc_addr_config = 8'h74; enc_data_config = 20'hA0370; // 0x74: len=10, code=1101110000
    @(posedge clk); enc_addr_config = 8'h75; enc_data_config = 20'hA0371; // 0x75: len=10, code=1101110001
    @(posedge clk); enc_addr_config = 8'h76; enc_data_config = 20'hA0372; // 0x76: len=10, code=1101110010
    @(posedge clk); enc_addr_config = 8'h77; enc_data_config = 20'hA0373; // 0x77: len=10, code=1101110011
    @(posedge clk); enc_addr_config = 8'h78; enc_data_config = 20'hA0374; // 0x78: len=10, code=1101110100
    @(posedge clk); enc_addr_config = 8'h79; enc_data_config = 20'hA0375; // 0x79: len=10, code=1101110101
    @(posedge clk); enc_addr_config = 8'h7A; enc_data_config = 20'hA0376; // 0x7A: len=10, code=1101110110
    @(posedge clk); enc_addr_config = 8'h7B; enc_data_config = 20'hA0377; // 0x7B: len=10, code=1101110111
    @(posedge clk); enc_addr_config = 8'h7C; enc_data_config = 20'hA0378; // 0x7C: len=10, code=1101111000
    @(posedge clk); enc_addr_config = 8'h7D; enc_data_config = 20'hA0379; // 0x7D: len=10, code=1101111001
    @(posedge clk); enc_addr_config = 8'h7E; enc_data_config = 20'hA037A; // 0x7E: len=10, code=1101111010
    @(posedge clk); enc_addr_config = 8'h7F; enc_data_config = 20'hA037B; // 0x7F: len=10, code=1101111011
    @(posedge clk); enc_addr_config = 8'h80; enc_data_config = 20'h40009; // 0x80: len=4, code=1001
    @(posedge clk); enc_addr_config = 8'h81; enc_data_config = 20'hA037C; // 0x81: len=10, code=1101111100
    @(posedge clk); enc_addr_config = 8'h82; enc_data_config = 20'hA037D; // 0x82: len=10, code=1101111101
    @(posedge clk); enc_addr_config = 8'h83; enc_data_config = 20'hA037E; // 0x83: len=10, code=1101111110
    @(posedge clk); enc_addr_config = 8'h84; enc_data_config = 20'hA037F; // 0x84: len=10, code=1101111111
    @(posedge clk); enc_addr_config = 8'h85; enc_data_config = 20'hA0380; // 0x85: len=10, code=1110000000
    @(posedge clk); enc_addr_config = 8'h86; enc_data_config = 20'hA0381; // 0x86: len=10, code=1110000001
    @(posedge clk); enc_addr_config = 8'h87; enc_data_config = 20'hA0382; // 0x87: len=10, code=1110000010
    @(posedge clk); enc_addr_config = 8'h88; enc_data_config = 20'hA0383; // 0x88: len=10, code=1110000011
    @(posedge clk); enc_addr_config = 8'h89; enc_data_config = 20'hA0384; // 0x89: len=10, code=1110000100
    @(posedge clk); enc_addr_config = 8'h8A; enc_data_config = 20'hA0385; // 0x8A: len=10, code=1110000101
    @(posedge clk); enc_addr_config = 8'h8B; enc_data_config = 20'hA0386; // 0x8B: len=10, code=1110000110
    @(posedge clk); enc_addr_config = 8'h8C; enc_data_config = 20'hA0387; // 0x8C: len=10, code=1110000111
    @(posedge clk); enc_addr_config = 8'h8D; enc_data_config = 20'hA0388; // 0x8D: len=10, code=1110001000
    @(posedge clk); enc_addr_config = 8'h8E; enc_data_config = 20'hA0389; // 0x8E: len=10, code=1110001001
    @(posedge clk); enc_addr_config = 8'h8F; enc_data_config = 20'hA038A; // 0x8F: len=10, code=1110001010
    @(posedge clk); enc_addr_config = 8'h90; enc_data_config = 20'hA038B; // 0x90: len=10, code=1110001011
    @(posedge clk); enc_addr_config = 8'h91; enc_data_config = 20'hA038C; // 0x91: len=10, code=1110001100
    @(posedge clk); enc_addr_config = 8'h92; enc_data_config = 20'hA038D; // 0x92: len=10, code=1110001101
    @(posedge clk); enc_addr_config = 8'h93; enc_data_config = 20'hA038E; // 0x93: len=10, code=1110001110
    @(posedge clk); enc_addr_config = 8'h94; enc_data_config = 20'hA038F; // 0x94: len=10, code=1110001111
    @(posedge clk); enc_addr_config = 8'h95; enc_data_config = 20'hA0390; // 0x95: len=10, code=1110010000
    @(posedge clk); enc_addr_config = 8'h96; enc_data_config = 20'hA0391; // 0x96: len=10, code=1110010001
    @(posedge clk); enc_addr_config = 8'h97; enc_data_config = 20'hA0392; // 0x97: len=10, code=1110010010
    @(posedge clk); enc_addr_config = 8'h98; enc_data_config = 20'hA0393; // 0x98: len=10, code=1110010011
    @(posedge clk); enc_addr_config = 8'h99; enc_data_config = 20'hA0394; // 0x99: len=10, code=1110010100
    @(posedge clk); enc_addr_config = 8'h9A; enc_data_config = 20'hA0395; // 0x9A: len=10, code=1110010101
    @(posedge clk); enc_addr_config = 8'h9B; enc_data_config = 20'hA0396; // 0x9B: len=10, code=1110010110
    @(posedge clk); enc_addr_config = 8'h9C; enc_data_config = 20'hA0397; // 0x9C: len=10, code=1110010111
    @(posedge clk); enc_addr_config = 8'h9D; enc_data_config = 20'hA0398; // 0x9D: len=10, code=1110011000
    @(posedge clk); enc_addr_config = 8'h9E; enc_data_config = 20'hA0399; // 0x9E: len=10, code=1110011001
    @(posedge clk); enc_addr_config = 8'h9F; enc_data_config = 20'hA039A; // 0x9F: len=10, code=1110011010
    @(posedge clk); enc_addr_config = 8'hA0; enc_data_config = 20'hA039B; // 0xA0: len=10, code=1110011011
    @(posedge clk); enc_addr_config = 8'hA1; enc_data_config = 20'hA039C; // 0xA1: len=10, code=1110011100
    @(posedge clk); enc_addr_config = 8'hA2; enc_data_config = 20'hA039D; // 0xA2: len=10, code=1110011101
    @(posedge clk); enc_addr_config = 8'hA3; enc_data_config = 20'hA039E; // 0xA3: len=10, code=1110011110
    @(posedge clk); enc_addr_config = 8'hA4; enc_data_config = 20'hA039F; // 0xA4: len=10, code=1110011111
    @(posedge clk); enc_addr_config = 8'hA5; enc_data_config = 20'hA03A0; // 0xA5: len=10, code=1110100000
    @(posedge clk); enc_addr_config = 8'hA6; enc_data_config = 20'hA03A1; // 0xA6: len=10, code=1110100001
    @(posedge clk); enc_addr_config = 8'hA7; enc_data_config = 20'hA03A2; // 0xA7: len=10, code=1110100010
    @(posedge clk); enc_addr_config = 8'hA8; enc_data_config = 20'hA03A3; // 0xA8: len=10, code=1110100011
    @(posedge clk); enc_addr_config = 8'hA9; enc_data_config = 20'hA03A4; // 0xA9: len=10, code=1110100100
    @(posedge clk); enc_addr_config = 8'hAA; enc_data_config = 20'hA03A5; // 0xAA: len=10, code=1110100101
    @(posedge clk); enc_addr_config = 8'hAB; enc_data_config = 20'hA03A6; // 0xAB: len=10, code=1110100110
    @(posedge clk); enc_addr_config = 8'hAC; enc_data_config = 20'hA03A7; // 0xAC: len=10, code=1110100111
    @(posedge clk); enc_addr_config = 8'hAD; enc_data_config = 20'hA03A8; // 0xAD: len=10, code=1110101000
    @(posedge clk); enc_addr_config = 8'hAE; enc_data_config = 20'hA03A9; // 0xAE: len=10, code=1110101001
    @(posedge clk); enc_addr_config = 8'hAF; enc_data_config = 20'hA03AA; // 0xAF: len=10, code=1110101010
    @(posedge clk); enc_addr_config = 8'hB0; enc_data_config = 20'hA03AB; // 0xB0: len=10, code=1110101011
    @(posedge clk); enc_addr_config = 8'hB1; enc_data_config = 20'hA03AC; // 0xB1: len=10, code=1110101100
    @(posedge clk); enc_addr_config = 8'hB2; enc_data_config = 20'hA03AD; // 0xB2: len=10, code=1110101101
    @(posedge clk); enc_addr_config = 8'hB3; enc_data_config = 20'hA03AE; // 0xB3: len=10, code=1110101110
    @(posedge clk); enc_addr_config = 8'hB4; enc_data_config = 20'hA03AF; // 0xB4: len=10, code=1110101111
    @(posedge clk); enc_addr_config = 8'hB5; enc_data_config = 20'hA03B0; // 0xB5: len=10, code=1110110000
    @(posedge clk); enc_addr_config = 8'hB6; enc_data_config = 20'hA03B1; // 0xB6: len=10, code=1110110001
    @(posedge clk); enc_addr_config = 8'hB7; enc_data_config = 20'hA03B2; // 0xB7: len=10, code=1110110010
    @(posedge clk); enc_addr_config = 8'hB8; enc_data_config = 20'hA03B3; // 0xB8: len=10, code=1110110011
    @(posedge clk); enc_addr_config = 8'hB9; enc_data_config = 20'hA03B4; // 0xB9: len=10, code=1110110100
    @(posedge clk); enc_addr_config = 8'hBA; enc_data_config = 20'hA03B5; // 0xBA: len=10, code=1110110101
    @(posedge clk); enc_addr_config = 8'hBB; enc_data_config = 20'hA03B6; // 0xBB: len=10, code=1110110110
    @(posedge clk); enc_addr_config = 8'hBC; enc_data_config = 20'hA03B7; // 0xBC: len=10, code=1110110111
    @(posedge clk); enc_addr_config = 8'hBD; enc_data_config = 20'hA03B8; // 0xBD: len=10, code=1110111000
    @(posedge clk); enc_addr_config = 8'hBE; enc_data_config = 20'hA03B9; // 0xBE: len=10, code=1110111001
    @(posedge clk); enc_addr_config = 8'hBF; enc_data_config = 20'h50015; // 0xBF: len=5, code=10101
    @(posedge clk); enc_addr_config = 8'hC0; enc_data_config = 20'h50016; // 0xC0: len=5, code=10110
    @(posedge clk); enc_addr_config = 8'hC1; enc_data_config = 20'hA03BA; // 0xC1: len=10, code=1110111010
    @(posedge clk); enc_addr_config = 8'hC2; enc_data_config = 20'hA03BB; // 0xC2: len=10, code=1110111011
    @(posedge clk); enc_addr_config = 8'hC3; enc_data_config = 20'hA03BC; // 0xC3: len=10, code=1110111100
    @(posedge clk); enc_addr_config = 8'hC4; enc_data_config = 20'hA03BD; // 0xC4: len=10, code=1110111101
    @(posedge clk); enc_addr_config = 8'hC5; enc_data_config = 20'hA03BE; // 0xC5: len=10, code=1110111110
    @(posedge clk); enc_addr_config = 8'hC6; enc_data_config = 20'hA03BF; // 0xC6: len=10, code=1110111111
    @(posedge clk); enc_addr_config = 8'hC7; enc_data_config = 20'hA03C0; // 0xC7: len=10, code=1111000000
    @(posedge clk); enc_addr_config = 8'hC8; enc_data_config = 20'hA03C1; // 0xC8: len=10, code=1111000001
    @(posedge clk); enc_addr_config = 8'hC9; enc_data_config = 20'hA03C2; // 0xC9: len=10, code=1111000010
    @(posedge clk); enc_addr_config = 8'hCA; enc_data_config = 20'hA03C3; // 0xCA: len=10, code=1111000011
    @(posedge clk); enc_addr_config = 8'hCB; enc_data_config = 20'hA03C4; // 0xCB: len=10, code=1111000100
    @(posedge clk); enc_addr_config = 8'hCC; enc_data_config = 20'hA03C5; // 0xCC: len=10, code=1111000101
    @(posedge clk); enc_addr_config = 8'hCD; enc_data_config = 20'hA03C6; // 0xCD: len=10, code=1111000110
    @(posedge clk); enc_addr_config = 8'hCE; enc_data_config = 20'hA03C7; // 0xCE: len=10, code=1111000111
    @(posedge clk); enc_addr_config = 8'hCF; enc_data_config = 20'hA03C8; // 0xCF: len=10, code=1111001000
    @(posedge clk); enc_addr_config = 8'hD0; enc_data_config = 20'hA03C9; // 0xD0: len=10, code=1111001001
    @(posedge clk); enc_addr_config = 8'hD1; enc_data_config = 20'hA03CA; // 0xD1: len=10, code=1111001010
    @(posedge clk); enc_addr_config = 8'hD2; enc_data_config = 20'hA03CB; // 0xD2: len=10, code=1111001011
    @(posedge clk); enc_addr_config = 8'hD3; enc_data_config = 20'hA03CC; // 0xD3: len=10, code=1111001100
    @(posedge clk); enc_addr_config = 8'hD4; enc_data_config = 20'hA03CD; // 0xD4: len=10, code=1111001101
    @(posedge clk); enc_addr_config = 8'hD5; enc_data_config = 20'hA03CE; // 0xD5: len=10, code=1111001110
    @(posedge clk); enc_addr_config = 8'hD6; enc_data_config = 20'hA03CF; // 0xD6: len=10, code=1111001111
    @(posedge clk); enc_addr_config = 8'hD7; enc_data_config = 20'hA03D0; // 0xD7: len=10, code=1111010000
    @(posedge clk); enc_addr_config = 8'hD8; enc_data_config = 20'hA03D1; // 0xD8: len=10, code=1111010001
    @(posedge clk); enc_addr_config = 8'hD9; enc_data_config = 20'hA03D2; // 0xD9: len=10, code=1111010010
    @(posedge clk); enc_addr_config = 8'hDA; enc_data_config = 20'hA03D3; // 0xDA: len=10, code=1111010011
    @(posedge clk); enc_addr_config = 8'hDB; enc_data_config = 20'hA03D4; // 0xDB: len=10, code=1111010100
    @(posedge clk); enc_addr_config = 8'hDC; enc_data_config = 20'hA03D5; // 0xDC: len=10, code=1111010101
    @(posedge clk); enc_addr_config = 8'hDD; enc_data_config = 20'hA03D6; // 0xDD: len=10, code=1111010110
    @(posedge clk); enc_addr_config = 8'hDE; enc_data_config = 20'hA03D7; // 0xDE: len=10, code=1111010111
    @(posedge clk); enc_addr_config = 8'hDF; enc_data_config = 20'hA03D8; // 0xDF: len=10, code=1111011000
    @(posedge clk); enc_addr_config = 8'hE0; enc_data_config = 20'hA03D9; // 0xE0: len=10, code=1111011001
    @(posedge clk); enc_addr_config = 8'hE1; enc_data_config = 20'hA03DA; // 0xE1: len=10, code=1111011010
    @(posedge clk); enc_addr_config = 8'hE2; enc_data_config = 20'hA03DB; // 0xE2: len=10, code=1111011011
    @(posedge clk); enc_addr_config = 8'hE3; enc_data_config = 20'hA03DC; // 0xE3: len=10, code=1111011100
    @(posedge clk); enc_addr_config = 8'hE4; enc_data_config = 20'hA03DD; // 0xE4: len=10, code=1111011101
    @(posedge clk); enc_addr_config = 8'hE5; enc_data_config = 20'hA03DE; // 0xE5: len=10, code=1111011110
    @(posedge clk); enc_addr_config = 8'hE6; enc_data_config = 20'hA03DF; // 0xE6: len=10, code=1111011111
    @(posedge clk); enc_addr_config = 8'hE7; enc_data_config = 20'hA03E0; // 0xE7: len=10, code=1111100000
    @(posedge clk); enc_addr_config = 8'hE8; enc_data_config = 20'hA03E1; // 0xE8: len=10, code=1111100001
    @(posedge clk); enc_addr_config = 8'hE9; enc_data_config = 20'hA03E2; // 0xE9: len=10, code=1111100010
    @(posedge clk); enc_addr_config = 8'hEA; enc_data_config = 20'hA03E3; // 0xEA: len=10, code=1111100011
    @(posedge clk); enc_addr_config = 8'hEB; enc_data_config = 20'hA03E4; // 0xEB: len=10, code=1111100100
    @(posedge clk); enc_addr_config = 8'hEC; enc_data_config = 20'hA03E5; // 0xEC: len=10, code=1111100101
    @(posedge clk); enc_addr_config = 8'hED; enc_data_config = 20'hA03E6; // 0xED: len=10, code=1111100110
    @(posedge clk); enc_addr_config = 8'hEE; enc_data_config = 20'hA03E7; // 0xEE: len=10, code=1111100111
    @(posedge clk); enc_addr_config = 8'hEF; enc_data_config = 20'hA03E8; // 0xEF: len=10, code=1111101000
    @(posedge clk); enc_addr_config = 8'hF0; enc_data_config = 20'hA03E9; // 0xF0: len=10, code=1111101001
    @(posedge clk); enc_addr_config = 8'hF1; enc_data_config = 20'hA03EA; // 0xF1: len=10, code=1111101010
    @(posedge clk); enc_addr_config = 8'hF2; enc_data_config = 20'hA03EB; // 0xF2: len=10, code=1111101011
    @(posedge clk); enc_addr_config = 8'hF3; enc_data_config = 20'hA03EC; // 0xF3: len=10, code=1111101100
    @(posedge clk); enc_addr_config = 8'hF4; enc_data_config = 20'hA03ED; // 0xF4: len=10, code=1111101101
    @(posedge clk); enc_addr_config = 8'hF5; enc_data_config = 20'hA03EE; // 0xF5: len=10, code=1111101110
    @(posedge clk); enc_addr_config = 8'hF6; enc_data_config = 20'hA03EF; // 0xF6: len=10, code=1111101111
    @(posedge clk); enc_addr_config = 8'hF7; enc_data_config = 20'hA03F0; // 0xF7: len=10, code=1111110000
    @(posedge clk); enc_addr_config = 8'hF8; enc_data_config = 20'hA03F1; // 0xF8: len=10, code=1111110001
    @(posedge clk); enc_addr_config = 8'hF9; enc_data_config = 20'hA03F2; // 0xF9: len=10, code=1111110010
    @(posedge clk); enc_addr_config = 8'hFA; enc_data_config = 20'hA03F3; // 0xFA: len=10, code=1111110011
    @(posedge clk); enc_addr_config = 8'hFB; enc_data_config = 20'hA03F4; // 0xFB: len=10, code=1111110100
    @(posedge clk); enc_addr_config = 8'hFC; enc_data_config = 20'hA03F5; // 0xFC: len=10, code=1111110101
    @(posedge clk); enc_addr_config = 8'hFD; enc_data_config = 20'hA03F6; // 0xFD: len=10, code=1111110110
    @(posedge clk); enc_addr_config = 8'hFE; enc_data_config = 20'hA03F7; // 0xFE: len=10, code=1111110111
    @(posedge clk); enc_addr_config = 8'hFF; enc_data_config = 20'h9018E; // 0xFF: len=9, code=110001110
    @(posedge clk); enc_wr_en = 0;
end
endtask

task config_decoder_full();
begin
    dec_wr_en = 1;

    // first_code table (table_sel = 0)
    dec_table_sel = 2'd0;
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'h0000; // first_code[1]
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'hFFFF; // first_code[2]
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'hFFFF; // first_code[3]
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'h8000; // first_code[4]
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'hA000; // first_code[5]
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'hFFFF; // first_code[6]
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'hFFFF; // first_code[7]
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'hB800; // first_code[8]
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'hC700; // first_code[9]
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'hC780; // first_code[10]
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'hFE00; // first_code[11]
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'hFFFF; // first_code[12]
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'hFFFF; // first_code[13]
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'hFFFF; // first_code[14]
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'hFFFF; // first_code[15]
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'hFFFF; // first_code[16]

    // base table (table_sel = 1)
    dec_table_sel = 2'd1;
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'd0; // base[1]
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'd1; // base[2]
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'd1; // base[3]
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'd1; // base[4]
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'd3; // base[5]
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'd6; // base[6]
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'd6; // base[7]
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'd6; // base[8]
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'd21; // base[9]
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'd22; // base[10]
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'd240; // base[11]
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'd256; // base[12]
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'd256; // base[13]
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'd256; // base[14]
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'd256; // base[15]
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'd256; // base[16]
    @(posedge clk); // extra cycle before table_sel change

    // symbol_table (table_sel = 2)
    dec_table_sel = 2'd2;
    @(posedge clk); dec_addr_config = 8'd0; dec_data_config = 16'h0000; // [0] = 0x00
    @(posedge clk); dec_addr_config = 8'd1; dec_data_config = 16'h003F; // [1] = 0x3F
    @(posedge clk); dec_addr_config = 8'd2; dec_data_config = 16'h0080; // [2] = 0x80
    @(posedge clk); dec_addr_config = 8'd3; dec_data_config = 16'h0040; // [3] = 0x40
    @(posedge clk); dec_addr_config = 8'd4; dec_data_config = 16'h00BF; // [4] = 0xBF
    @(posedge clk); dec_addr_config = 8'd5; dec_data_config = 16'h00C0; // [5] = 0xC0
    @(posedge clk); dec_addr_config = 8'd6; dec_data_config = 16'h0001; // [6] = 0x01
    @(posedge clk); dec_addr_config = 8'd7; dec_data_config = 16'h0002; // [7] = 0x02
    @(posedge clk); dec_addr_config = 8'd8; dec_data_config = 16'h0003; // [8] = 0x03
    @(posedge clk); dec_addr_config = 8'd9; dec_data_config = 16'h0004; // [9] = 0x04
    @(posedge clk); dec_addr_config = 8'd10; dec_data_config = 16'h0005; // [10] = 0x05
    @(posedge clk); dec_addr_config = 8'd11; dec_data_config = 16'h0006; // [11] = 0x06
    @(posedge clk); dec_addr_config = 8'd12; dec_data_config = 16'h0007; // [12] = 0x07
    @(posedge clk); dec_addr_config = 8'd13; dec_data_config = 16'h0008; // [13] = 0x08
    @(posedge clk); dec_addr_config = 8'd14; dec_data_config = 16'h0009; // [14] = 0x09
    @(posedge clk); dec_addr_config = 8'd15; dec_data_config = 16'h000A; // [15] = 0x0A
    @(posedge clk); dec_addr_config = 8'd16; dec_data_config = 16'h000B; // [16] = 0x0B
    @(posedge clk); dec_addr_config = 8'd17; dec_data_config = 16'h000C; // [17] = 0x0C
    @(posedge clk); dec_addr_config = 8'd18; dec_data_config = 16'h000D; // [18] = 0x0D
    @(posedge clk); dec_addr_config = 8'd19; dec_data_config = 16'h000E; // [19] = 0x0E
    @(posedge clk); dec_addr_config = 8'd20; dec_data_config = 16'h000F; // [20] = 0x0F
    @(posedge clk); dec_addr_config = 8'd21; dec_data_config = 16'h00FF; // [21] = 0xFF
    @(posedge clk); dec_addr_config = 8'd22; dec_data_config = 16'h0020; // [22] = 0x20
    @(posedge clk); dec_addr_config = 8'd23; dec_data_config = 16'h0021; // [23] = 0x21
    @(posedge clk); dec_addr_config = 8'd24; dec_data_config = 16'h0022; // [24] = 0x22
    @(posedge clk); dec_addr_config = 8'd25; dec_data_config = 16'h0023; // [25] = 0x23
    @(posedge clk); dec_addr_config = 8'd26; dec_data_config = 16'h0024; // [26] = 0x24
    @(posedge clk); dec_addr_config = 8'd27; dec_data_config = 16'h0025; // [27] = 0x25
    @(posedge clk); dec_addr_config = 8'd28; dec_data_config = 16'h0026; // [28] = 0x26
    @(posedge clk); dec_addr_config = 8'd29; dec_data_config = 16'h0027; // [29] = 0x27
    @(posedge clk); dec_addr_config = 8'd30; dec_data_config = 16'h0028; // [30] = 0x28
    @(posedge clk); dec_addr_config = 8'd31; dec_data_config = 16'h0029; // [31] = 0x29
    @(posedge clk); dec_addr_config = 8'd32; dec_data_config = 16'h002A; // [32] = 0x2A
    @(posedge clk); dec_addr_config = 8'd33; dec_data_config = 16'h002B; // [33] = 0x2B
    @(posedge clk); dec_addr_config = 8'd34; dec_data_config = 16'h002C; // [34] = 0x2C
    @(posedge clk); dec_addr_config = 8'd35; dec_data_config = 16'h002D; // [35] = 0x2D
    @(posedge clk); dec_addr_config = 8'd36; dec_data_config = 16'h002E; // [36] = 0x2E
    @(posedge clk); dec_addr_config = 8'd37; dec_data_config = 16'h002F; // [37] = 0x2F
    @(posedge clk); dec_addr_config = 8'd38; dec_data_config = 16'h0030; // [38] = 0x30
    @(posedge clk); dec_addr_config = 8'd39; dec_data_config = 16'h0031; // [39] = 0x31
    @(posedge clk); dec_addr_config = 8'd40; dec_data_config = 16'h0032; // [40] = 0x32
    @(posedge clk); dec_addr_config = 8'd41; dec_data_config = 16'h0033; // [41] = 0x33
    @(posedge clk); dec_addr_config = 8'd42; dec_data_config = 16'h0034; // [42] = 0x34
    @(posedge clk); dec_addr_config = 8'd43; dec_data_config = 16'h0035; // [43] = 0x35
    @(posedge clk); dec_addr_config = 8'd44; dec_data_config = 16'h0036; // [44] = 0x36
    @(posedge clk); dec_addr_config = 8'd45; dec_data_config = 16'h0037; // [45] = 0x37
    @(posedge clk); dec_addr_config = 8'd46; dec_data_config = 16'h0038; // [46] = 0x38
    @(posedge clk); dec_addr_config = 8'd47; dec_data_config = 16'h0039; // [47] = 0x39
    @(posedge clk); dec_addr_config = 8'd48; dec_data_config = 16'h003A; // [48] = 0x3A
    @(posedge clk); dec_addr_config = 8'd49; dec_data_config = 16'h003B; // [49] = 0x3B
    @(posedge clk); dec_addr_config = 8'd50; dec_data_config = 16'h003C; // [50] = 0x3C
    @(posedge clk); dec_addr_config = 8'd51; dec_data_config = 16'h003D; // [51] = 0x3D
    @(posedge clk); dec_addr_config = 8'd52; dec_data_config = 16'h003E; // [52] = 0x3E
    @(posedge clk); dec_addr_config = 8'd53; dec_data_config = 16'h0041; // [53] = 0x41
    @(posedge clk); dec_addr_config = 8'd54; dec_data_config = 16'h0042; // [54] = 0x42
    @(posedge clk); dec_addr_config = 8'd55; dec_data_config = 16'h0043; // [55] = 0x43
    @(posedge clk); dec_addr_config = 8'd56; dec_data_config = 16'h0044; // [56] = 0x44
    @(posedge clk); dec_addr_config = 8'd57; dec_data_config = 16'h0045; // [57] = 0x45
    @(posedge clk); dec_addr_config = 8'd58; dec_data_config = 16'h0046; // [58] = 0x46
    @(posedge clk); dec_addr_config = 8'd59; dec_data_config = 16'h0047; // [59] = 0x47
    @(posedge clk); dec_addr_config = 8'd60; dec_data_config = 16'h0048; // [60] = 0x48
    @(posedge clk); dec_addr_config = 8'd61; dec_data_config = 16'h0049; // [61] = 0x49
    @(posedge clk); dec_addr_config = 8'd62; dec_data_config = 16'h004A; // [62] = 0x4A
    @(posedge clk); dec_addr_config = 8'd63; dec_data_config = 16'h004B; // [63] = 0x4B
    @(posedge clk); dec_addr_config = 8'd64; dec_data_config = 16'h004C; // [64] = 0x4C
    @(posedge clk); dec_addr_config = 8'd65; dec_data_config = 16'h004D; // [65] = 0x4D
    @(posedge clk); dec_addr_config = 8'd66; dec_data_config = 16'h004E; // [66] = 0x4E
    @(posedge clk); dec_addr_config = 8'd67; dec_data_config = 16'h004F; // [67] = 0x4F
    @(posedge clk); dec_addr_config = 8'd68; dec_data_config = 16'h0050; // [68] = 0x50
    @(posedge clk); dec_addr_config = 8'd69; dec_data_config = 16'h0051; // [69] = 0x51
    @(posedge clk); dec_addr_config = 8'd70; dec_data_config = 16'h0052; // [70] = 0x52
    @(posedge clk); dec_addr_config = 8'd71; dec_data_config = 16'h0053; // [71] = 0x53
    @(posedge clk); dec_addr_config = 8'd72; dec_data_config = 16'h0054; // [72] = 0x54
    @(posedge clk); dec_addr_config = 8'd73; dec_data_config = 16'h0055; // [73] = 0x55
    @(posedge clk); dec_addr_config = 8'd74; dec_data_config = 16'h0056; // [74] = 0x56
    @(posedge clk); dec_addr_config = 8'd75; dec_data_config = 16'h0057; // [75] = 0x57
    @(posedge clk); dec_addr_config = 8'd76; dec_data_config = 16'h0058; // [76] = 0x58
    @(posedge clk); dec_addr_config = 8'd77; dec_data_config = 16'h0059; // [77] = 0x59
    @(posedge clk); dec_addr_config = 8'd78; dec_data_config = 16'h005A; // [78] = 0x5A
    @(posedge clk); dec_addr_config = 8'd79; dec_data_config = 16'h005B; // [79] = 0x5B
    @(posedge clk); dec_addr_config = 8'd80; dec_data_config = 16'h005C; // [80] = 0x5C
    @(posedge clk); dec_addr_config = 8'd81; dec_data_config = 16'h005D; // [81] = 0x5D
    @(posedge clk); dec_addr_config = 8'd82; dec_data_config = 16'h005E; // [82] = 0x5E
    @(posedge clk); dec_addr_config = 8'd83; dec_data_config = 16'h005F; // [83] = 0x5F
    @(posedge clk); dec_addr_config = 8'd84; dec_data_config = 16'h0060; // [84] = 0x60
    @(posedge clk); dec_addr_config = 8'd85; dec_data_config = 16'h0061; // [85] = 0x61
    @(posedge clk); dec_addr_config = 8'd86; dec_data_config = 16'h0062; // [86] = 0x62
    @(posedge clk); dec_addr_config = 8'd87; dec_data_config = 16'h0063; // [87] = 0x63
    @(posedge clk); dec_addr_config = 8'd88; dec_data_config = 16'h0064; // [88] = 0x64
    @(posedge clk); dec_addr_config = 8'd89; dec_data_config = 16'h0065; // [89] = 0x65
    @(posedge clk); dec_addr_config = 8'd90; dec_data_config = 16'h0066; // [90] = 0x66
    @(posedge clk); dec_addr_config = 8'd91; dec_data_config = 16'h0067; // [91] = 0x67
    @(posedge clk); dec_addr_config = 8'd92; dec_data_config = 16'h0068; // [92] = 0x68
    @(posedge clk); dec_addr_config = 8'd93; dec_data_config = 16'h0069; // [93] = 0x69
    @(posedge clk); dec_addr_config = 8'd94; dec_data_config = 16'h006A; // [94] = 0x6A
    @(posedge clk); dec_addr_config = 8'd95; dec_data_config = 16'h006B; // [95] = 0x6B
    @(posedge clk); dec_addr_config = 8'd96; dec_data_config = 16'h006C; // [96] = 0x6C
    @(posedge clk); dec_addr_config = 8'd97; dec_data_config = 16'h006D; // [97] = 0x6D
    @(posedge clk); dec_addr_config = 8'd98; dec_data_config = 16'h006E; // [98] = 0x6E
    @(posedge clk); dec_addr_config = 8'd99; dec_data_config = 16'h006F; // [99] = 0x6F
    @(posedge clk); dec_addr_config = 8'd100; dec_data_config = 16'h0070; // [100] = 0x70
    @(posedge clk); dec_addr_config = 8'd101; dec_data_config = 16'h0071; // [101] = 0x71
    @(posedge clk); dec_addr_config = 8'd102; dec_data_config = 16'h0072; // [102] = 0x72
    @(posedge clk); dec_addr_config = 8'd103; dec_data_config = 16'h0073; // [103] = 0x73
    @(posedge clk); dec_addr_config = 8'd104; dec_data_config = 16'h0074; // [104] = 0x74
    @(posedge clk); dec_addr_config = 8'd105; dec_data_config = 16'h0075; // [105] = 0x75
    @(posedge clk); dec_addr_config = 8'd106; dec_data_config = 16'h0076; // [106] = 0x76
    @(posedge clk); dec_addr_config = 8'd107; dec_data_config = 16'h0077; // [107] = 0x77
    @(posedge clk); dec_addr_config = 8'd108; dec_data_config = 16'h0078; // [108] = 0x78
    @(posedge clk); dec_addr_config = 8'd109; dec_data_config = 16'h0079; // [109] = 0x79
    @(posedge clk); dec_addr_config = 8'd110; dec_data_config = 16'h007A; // [110] = 0x7A
    @(posedge clk); dec_addr_config = 8'd111; dec_data_config = 16'h007B; // [111] = 0x7B
    @(posedge clk); dec_addr_config = 8'd112; dec_data_config = 16'h007C; // [112] = 0x7C
    @(posedge clk); dec_addr_config = 8'd113; dec_data_config = 16'h007D; // [113] = 0x7D
    @(posedge clk); dec_addr_config = 8'd114; dec_data_config = 16'h007E; // [114] = 0x7E
    @(posedge clk); dec_addr_config = 8'd115; dec_data_config = 16'h007F; // [115] = 0x7F
    @(posedge clk); dec_addr_config = 8'd116; dec_data_config = 16'h0081; // [116] = 0x81
    @(posedge clk); dec_addr_config = 8'd117; dec_data_config = 16'h0082; // [117] = 0x82
    @(posedge clk); dec_addr_config = 8'd118; dec_data_config = 16'h0083; // [118] = 0x83
    @(posedge clk); dec_addr_config = 8'd119; dec_data_config = 16'h0084; // [119] = 0x84
    @(posedge clk); dec_addr_config = 8'd120; dec_data_config = 16'h0085; // [120] = 0x85
    @(posedge clk); dec_addr_config = 8'd121; dec_data_config = 16'h0086; // [121] = 0x86
    @(posedge clk); dec_addr_config = 8'd122; dec_data_config = 16'h0087; // [122] = 0x87
    @(posedge clk); dec_addr_config = 8'd123; dec_data_config = 16'h0088; // [123] = 0x88
    @(posedge clk); dec_addr_config = 8'd124; dec_data_config = 16'h0089; // [124] = 0x89
    @(posedge clk); dec_addr_config = 8'd125; dec_data_config = 16'h008A; // [125] = 0x8A
    @(posedge clk); dec_addr_config = 8'd126; dec_data_config = 16'h008B; // [126] = 0x8B
    @(posedge clk); dec_addr_config = 8'd127; dec_data_config = 16'h008C; // [127] = 0x8C
    @(posedge clk); dec_addr_config = 8'd128; dec_data_config = 16'h008D; // [128] = 0x8D
    @(posedge clk); dec_addr_config = 8'd129; dec_data_config = 16'h008E; // [129] = 0x8E
    @(posedge clk); dec_addr_config = 8'd130; dec_data_config = 16'h008F; // [130] = 0x8F
    @(posedge clk); dec_addr_config = 8'd131; dec_data_config = 16'h0090; // [131] = 0x90
    @(posedge clk); dec_addr_config = 8'd132; dec_data_config = 16'h0091; // [132] = 0x91
    @(posedge clk); dec_addr_config = 8'd133; dec_data_config = 16'h0092; // [133] = 0x92
    @(posedge clk); dec_addr_config = 8'd134; dec_data_config = 16'h0093; // [134] = 0x93
    @(posedge clk); dec_addr_config = 8'd135; dec_data_config = 16'h0094; // [135] = 0x94
    @(posedge clk); dec_addr_config = 8'd136; dec_data_config = 16'h0095; // [136] = 0x95
    @(posedge clk); dec_addr_config = 8'd137; dec_data_config = 16'h0096; // [137] = 0x96
    @(posedge clk); dec_addr_config = 8'd138; dec_data_config = 16'h0097; // [138] = 0x97
    @(posedge clk); dec_addr_config = 8'd139; dec_data_config = 16'h0098; // [139] = 0x98
    @(posedge clk); dec_addr_config = 8'd140; dec_data_config = 16'h0099; // [140] = 0x99
    @(posedge clk); dec_addr_config = 8'd141; dec_data_config = 16'h009A; // [141] = 0x9A
    @(posedge clk); dec_addr_config = 8'd142; dec_data_config = 16'h009B; // [142] = 0x9B
    @(posedge clk); dec_addr_config = 8'd143; dec_data_config = 16'h009C; // [143] = 0x9C
    @(posedge clk); dec_addr_config = 8'd144; dec_data_config = 16'h009D; // [144] = 0x9D
    @(posedge clk); dec_addr_config = 8'd145; dec_data_config = 16'h009E; // [145] = 0x9E
    @(posedge clk); dec_addr_config = 8'd146; dec_data_config = 16'h009F; // [146] = 0x9F
    @(posedge clk); dec_addr_config = 8'd147; dec_data_config = 16'h00A0; // [147] = 0xA0
    @(posedge clk); dec_addr_config = 8'd148; dec_data_config = 16'h00A1; // [148] = 0xA1
    @(posedge clk); dec_addr_config = 8'd149; dec_data_config = 16'h00A2; // [149] = 0xA2
    @(posedge clk); dec_addr_config = 8'd150; dec_data_config = 16'h00A3; // [150] = 0xA3
    @(posedge clk); dec_addr_config = 8'd151; dec_data_config = 16'h00A4; // [151] = 0xA4
    @(posedge clk); dec_addr_config = 8'd152; dec_data_config = 16'h00A5; // [152] = 0xA5
    @(posedge clk); dec_addr_config = 8'd153; dec_data_config = 16'h00A6; // [153] = 0xA6
    @(posedge clk); dec_addr_config = 8'd154; dec_data_config = 16'h00A7; // [154] = 0xA7
    @(posedge clk); dec_addr_config = 8'd155; dec_data_config = 16'h00A8; // [155] = 0xA8
    @(posedge clk); dec_addr_config = 8'd156; dec_data_config = 16'h00A9; // [156] = 0xA9
    @(posedge clk); dec_addr_config = 8'd157; dec_data_config = 16'h00AA; // [157] = 0xAA
    @(posedge clk); dec_addr_config = 8'd158; dec_data_config = 16'h00AB; // [158] = 0xAB
    @(posedge clk); dec_addr_config = 8'd159; dec_data_config = 16'h00AC; // [159] = 0xAC
    @(posedge clk); dec_addr_config = 8'd160; dec_data_config = 16'h00AD; // [160] = 0xAD
    @(posedge clk); dec_addr_config = 8'd161; dec_data_config = 16'h00AE; // [161] = 0xAE
    @(posedge clk); dec_addr_config = 8'd162; dec_data_config = 16'h00AF; // [162] = 0xAF
    @(posedge clk); dec_addr_config = 8'd163; dec_data_config = 16'h00B0; // [163] = 0xB0
    @(posedge clk); dec_addr_config = 8'd164; dec_data_config = 16'h00B1; // [164] = 0xB1
    @(posedge clk); dec_addr_config = 8'd165; dec_data_config = 16'h00B2; // [165] = 0xB2
    @(posedge clk); dec_addr_config = 8'd166; dec_data_config = 16'h00B3; // [166] = 0xB3
    @(posedge clk); dec_addr_config = 8'd167; dec_data_config = 16'h00B4; // [167] = 0xB4
    @(posedge clk); dec_addr_config = 8'd168; dec_data_config = 16'h00B5; // [168] = 0xB5
    @(posedge clk); dec_addr_config = 8'd169; dec_data_config = 16'h00B6; // [169] = 0xB6
    @(posedge clk); dec_addr_config = 8'd170; dec_data_config = 16'h00B7; // [170] = 0xB7
    @(posedge clk); dec_addr_config = 8'd171; dec_data_config = 16'h00B8; // [171] = 0xB8
    @(posedge clk); dec_addr_config = 8'd172; dec_data_config = 16'h00B9; // [172] = 0xB9
    @(posedge clk); dec_addr_config = 8'd173; dec_data_config = 16'h00BA; // [173] = 0xBA
    @(posedge clk); dec_addr_config = 8'd174; dec_data_config = 16'h00BB; // [174] = 0xBB
    @(posedge clk); dec_addr_config = 8'd175; dec_data_config = 16'h00BC; // [175] = 0xBC
    @(posedge clk); dec_addr_config = 8'd176; dec_data_config = 16'h00BD; // [176] = 0xBD
    @(posedge clk); dec_addr_config = 8'd177; dec_data_config = 16'h00BE; // [177] = 0xBE
    @(posedge clk); dec_addr_config = 8'd178; dec_data_config = 16'h00C1; // [178] = 0xC1
    @(posedge clk); dec_addr_config = 8'd179; dec_data_config = 16'h00C2; // [179] = 0xC2
    @(posedge clk); dec_addr_config = 8'd180; dec_data_config = 16'h00C3; // [180] = 0xC3
    @(posedge clk); dec_addr_config = 8'd181; dec_data_config = 16'h00C4; // [181] = 0xC4
    @(posedge clk); dec_addr_config = 8'd182; dec_data_config = 16'h00C5; // [182] = 0xC5
    @(posedge clk); dec_addr_config = 8'd183; dec_data_config = 16'h00C6; // [183] = 0xC6
    @(posedge clk); dec_addr_config = 8'd184; dec_data_config = 16'h00C7; // [184] = 0xC7
    @(posedge clk); dec_addr_config = 8'd185; dec_data_config = 16'h00C8; // [185] = 0xC8
    @(posedge clk); dec_addr_config = 8'd186; dec_data_config = 16'h00C9; // [186] = 0xC9
    @(posedge clk); dec_addr_config = 8'd187; dec_data_config = 16'h00CA; // [187] = 0xCA
    @(posedge clk); dec_addr_config = 8'd188; dec_data_config = 16'h00CB; // [188] = 0xCB
    @(posedge clk); dec_addr_config = 8'd189; dec_data_config = 16'h00CC; // [189] = 0xCC
    @(posedge clk); dec_addr_config = 8'd190; dec_data_config = 16'h00CD; // [190] = 0xCD
    @(posedge clk); dec_addr_config = 8'd191; dec_data_config = 16'h00CE; // [191] = 0xCE
    @(posedge clk); dec_addr_config = 8'd192; dec_data_config = 16'h00CF; // [192] = 0xCF
    @(posedge clk); dec_addr_config = 8'd193; dec_data_config = 16'h00D0; // [193] = 0xD0
    @(posedge clk); dec_addr_config = 8'd194; dec_data_config = 16'h00D1; // [194] = 0xD1
    @(posedge clk); dec_addr_config = 8'd195; dec_data_config = 16'h00D2; // [195] = 0xD2
    @(posedge clk); dec_addr_config = 8'd196; dec_data_config = 16'h00D3; // [196] = 0xD3
    @(posedge clk); dec_addr_config = 8'd197; dec_data_config = 16'h00D4; // [197] = 0xD4
    @(posedge clk); dec_addr_config = 8'd198; dec_data_config = 16'h00D5; // [198] = 0xD5
    @(posedge clk); dec_addr_config = 8'd199; dec_data_config = 16'h00D6; // [199] = 0xD6
    @(posedge clk); dec_addr_config = 8'd200; dec_data_config = 16'h00D7; // [200] = 0xD7
    @(posedge clk); dec_addr_config = 8'd201; dec_data_config = 16'h00D8; // [201] = 0xD8
    @(posedge clk); dec_addr_config = 8'd202; dec_data_config = 16'h00D9; // [202] = 0xD9
    @(posedge clk); dec_addr_config = 8'd203; dec_data_config = 16'h00DA; // [203] = 0xDA
    @(posedge clk); dec_addr_config = 8'd204; dec_data_config = 16'h00DB; // [204] = 0xDB
    @(posedge clk); dec_addr_config = 8'd205; dec_data_config = 16'h00DC; // [205] = 0xDC
    @(posedge clk); dec_addr_config = 8'd206; dec_data_config = 16'h00DD; // [206] = 0xDD
    @(posedge clk); dec_addr_config = 8'd207; dec_data_config = 16'h00DE; // [207] = 0xDE
    @(posedge clk); dec_addr_config = 8'd208; dec_data_config = 16'h00DF; // [208] = 0xDF
    @(posedge clk); dec_addr_config = 8'd209; dec_data_config = 16'h00E0; // [209] = 0xE0
    @(posedge clk); dec_addr_config = 8'd210; dec_data_config = 16'h00E1; // [210] = 0xE1
    @(posedge clk); dec_addr_config = 8'd211; dec_data_config = 16'h00E2; // [211] = 0xE2
    @(posedge clk); dec_addr_config = 8'd212; dec_data_config = 16'h00E3; // [212] = 0xE3
    @(posedge clk); dec_addr_config = 8'd213; dec_data_config = 16'h00E4; // [213] = 0xE4
    @(posedge clk); dec_addr_config = 8'd214; dec_data_config = 16'h00E5; // [214] = 0xE5
    @(posedge clk); dec_addr_config = 8'd215; dec_data_config = 16'h00E6; // [215] = 0xE6
    @(posedge clk); dec_addr_config = 8'd216; dec_data_config = 16'h00E7; // [216] = 0xE7
    @(posedge clk); dec_addr_config = 8'd217; dec_data_config = 16'h00E8; // [217] = 0xE8
    @(posedge clk); dec_addr_config = 8'd218; dec_data_config = 16'h00E9; // [218] = 0xE9
    @(posedge clk); dec_addr_config = 8'd219; dec_data_config = 16'h00EA; // [219] = 0xEA
    @(posedge clk); dec_addr_config = 8'd220; dec_data_config = 16'h00EB; // [220] = 0xEB
    @(posedge clk); dec_addr_config = 8'd221; dec_data_config = 16'h00EC; // [221] = 0xEC
    @(posedge clk); dec_addr_config = 8'd222; dec_data_config = 16'h00ED; // [222] = 0xED
    @(posedge clk); dec_addr_config = 8'd223; dec_data_config = 16'h00EE; // [223] = 0xEE
    @(posedge clk); dec_addr_config = 8'd224; dec_data_config = 16'h00EF; // [224] = 0xEF
    @(posedge clk); dec_addr_config = 8'd225; dec_data_config = 16'h00F0; // [225] = 0xF0
    @(posedge clk); dec_addr_config = 8'd226; dec_data_config = 16'h00F1; // [226] = 0xF1
    @(posedge clk); dec_addr_config = 8'd227; dec_data_config = 16'h00F2; // [227] = 0xF2
    @(posedge clk); dec_addr_config = 8'd228; dec_data_config = 16'h00F3; // [228] = 0xF3
    @(posedge clk); dec_addr_config = 8'd229; dec_data_config = 16'h00F4; // [229] = 0xF4
    @(posedge clk); dec_addr_config = 8'd230; dec_data_config = 16'h00F5; // [230] = 0xF5
    @(posedge clk); dec_addr_config = 8'd231; dec_data_config = 16'h00F6; // [231] = 0xF6
    @(posedge clk); dec_addr_config = 8'd232; dec_data_config = 16'h00F7; // [232] = 0xF7
    @(posedge clk); dec_addr_config = 8'd233; dec_data_config = 16'h00F8; // [233] = 0xF8
    @(posedge clk); dec_addr_config = 8'd234; dec_data_config = 16'h00F9; // [234] = 0xF9
    @(posedge clk); dec_addr_config = 8'd235; dec_data_config = 16'h00FA; // [235] = 0xFA
    @(posedge clk); dec_addr_config = 8'd236; dec_data_config = 16'h00FB; // [236] = 0xFB
    @(posedge clk); dec_addr_config = 8'd237; dec_data_config = 16'h00FC; // [237] = 0xFC
    @(posedge clk); dec_addr_config = 8'd238; dec_data_config = 16'h00FD; // [238] = 0xFD
    @(posedge clk); dec_addr_config = 8'd239; dec_data_config = 16'h00FE; // [239] = 0xFE
    @(posedge clk); dec_addr_config = 8'd240; dec_data_config = 16'h0010; // [240] = 0x10
    @(posedge clk); dec_addr_config = 8'd241; dec_data_config = 16'h0011; // [241] = 0x11
    @(posedge clk); dec_addr_config = 8'd242; dec_data_config = 16'h0012; // [242] = 0x12
    @(posedge clk); dec_addr_config = 8'd243; dec_data_config = 16'h0013; // [243] = 0x13
    @(posedge clk); dec_addr_config = 8'd244; dec_data_config = 16'h0014; // [244] = 0x14
    @(posedge clk); dec_addr_config = 8'd245; dec_data_config = 16'h0015; // [245] = 0x15
    @(posedge clk); dec_addr_config = 8'd246; dec_data_config = 16'h0016; // [246] = 0x16
    @(posedge clk); dec_addr_config = 8'd247; dec_data_config = 16'h0017; // [247] = 0x17
    @(posedge clk); dec_addr_config = 8'd248; dec_data_config = 16'h0018; // [248] = 0x18
    @(posedge clk); dec_addr_config = 8'd249; dec_data_config = 16'h0019; // [249] = 0x19
    @(posedge clk); dec_addr_config = 8'd250; dec_data_config = 16'h001A; // [250] = 0x1A
    @(posedge clk); dec_addr_config = 8'd251; dec_data_config = 16'h001B; // [251] = 0x1B
    @(posedge clk); dec_addr_config = 8'd252; dec_data_config = 16'h001C; // [252] = 0x1C
    @(posedge clk); dec_addr_config = 8'd253; dec_data_config = 16'h001D; // [253] = 0x1D
    @(posedge clk); dec_addr_config = 8'd254; dec_data_config = 16'h001E; // [254] = 0x1E
    @(posedge clk); dec_addr_config = 8'd255; dec_data_config = 16'h001F; // [255] = 0x1F

    @(posedge clk); dec_wr_en = 0;
end
endtask

